### ISSUE TITLE
HonoClient: Error processing "not accepted by peer" response (0.9-M2)

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1020]
When processing the _delivery update_ received after having sent a message, the _Sender_ component of `HonoClient` (ie. `AbstractSender` and `AbstractRequestResponseClient`) produces an `IllegalArgumentException`:
````
12:15:46.525 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.EventSenderImpl - message [message ID: EventSenderImpl-7] not accepted by peer, remote state: Released{}
12:15:46.525 [vert.x-eventloop-thread-0] ERROR o.e.hono.client.impl.EventSenderImpl - error handling delivery update
java.lang.IllegalArgumentException: client error code must be >= 400 and < 500
	at org.eclipse.hono.client.ClientErrorException.<init>(ClientErrorException.java:68)
	at org.eclipse.hono.client.ClientErrorException.<init>(ClientErrorException.java:32)
	at org.eclipse.hono.client.impl.AbstractSender.lambda$sendMessageAndWaitForOutcome$6(AbstractSender.java:458)
	at io.vertx.proton.impl.ProtonDeliveryImpl.fireUpdate(ProtonDeliveryImpl.java:153)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:160)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:392)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:225)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:123)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:370)
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:386)
````
Extra exception handling has been added to get this stacktrace - the exception is not logged with the standard Hono build.

This exception leads the `ProtonTransport` associated with the corresponding AMQP connection to not handle any further AMQP events, which will lead to followup errors (e.g. timeouts when trying to create a new sender).

**Comment by calohmn** [comment]
Added https://github.com/vert-x3/vertx-proton/issues/94 to improve error logging in such a scenario.
