### ISSUE TITLE
Deploying 0.9 adapters: openSSL is not available

### ISSUE THREAD

**Issue by BobClaerhout** [eclipse/hono#1075]
I'm trying to deploy version 0.9 of Hono. When I do, I'm getting following error in all adapters: 
```

15:29:51.121 [main] ERROR o.e.h.a.m.i.Application$$EnhancerBySpringCGLIB$$58f7a596 - exception occurred during startup, shutting down ...

15:30:01.477 [main] INFO  o.e.hono.client.impl.HonoClientImpl - using OpenTracing implementation [io.opentracing.noop.NoopTracerImpl]
--
  | 15:30:01.491 [vert.x-eventloop-thread-0] INFO  o.e.h.c.RequestResponseClientConfigProperties - loading credentials for [hono-service-device-registry.hono.svc] from [/etc/secrets/registry.properties]
  | 15:30:01.890 [vert.x-eventloop-thread-0] INFO  o.e.h.config.ClientConfigProperties - loading credentials for [messaging-aloxy.enmasse-infra.svc] from [/etc/secrets/downstream.properties]
  | 15:30:01.891 [vert.x-eventloop-thread-0] INFO  o.e.h.c.RequestResponseClientConfigProperties - loading credentials for [hono-service-device-registry.hono.svc] from [/etc/secrets/registry.properties]
  | 15:30:01.896 [vert.x-eventloop-thread-0] INFO  o.e.h.c.RequestResponseClientConfigProperties - loading credentials for [hono-service-device-registry.hono.svc] from [/etc/secrets/registry.properties]
  | 15:30:01.899 [vert.x-eventloop-thread-0] INFO  o.e.h.config.ClientConfigProperties - loading credentials for [messaging-aloxy.enmasse-infra.svc] from [/etc/secrets/downstream.properties]
  | 15:30:01.900 [vert.x-eventloop-thread-0] INFO  o.e.h.a.a.VertxBasedAmqpProtocolAdapter - Vertx native support: false
  | 15:30:01.905 [vert.x-eventloop-thread-0] INFO  o.e.h.a.a.VertxBasedAmqpProtocolAdapter - Server uses secure standard port 5671
  | 15:30:01.905 [vert.x-eventloop-thread-0] INFO  o.e.h.a.a.VertxBasedAmqpProtocolAdapter - using OpenSSL [version: null] instead of JDK's default SSL engine
  | 15:30:01.907 [vert.x-eventloop-thread-0] INFO  o.e.h.a.a.VertxBasedAmqpProtocolAdapter - enabling secure protocol [TLSv1.2]
  | 15:30:01.911 [vert.x-eventloop-thread-0] INFO  o.e.h.a.a.VertxBasedAmqpProtocolAdapter - enabling client authentication using certificates [org.eclipse.hono.service.auth.ValidityBasedTrustOptions]
  | 15:30:01.923 [main] ERROR o.e.h.a.a.Application$$EnhancerBySpringCGLIB$$5a7ec18d - exception occurred during startup, shutting down ...

--
  | java.util.concurrent.ExecutionException: io.vertx.core.VertxException: OpenSSL is not available
  | at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
  | at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
  | at org.eclipse.hono.service.AbstractApplication.run(AbstractApplication.java:168)
  | at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:723)
  | at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:713)
  | at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
  | at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
  | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
  | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
  | at org.eclipse.hono.adapter.mqtt.impl.Application.main(Application.java:36)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  | at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
  | at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
  | at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
  | at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:595)
  | Caused by: io.vertx.core.VertxException: OpenSSL is not available
  | at io.vertx.core.net.impl.SSLHelper.resolveEngineOptions(SSLHelper.java:76)
  | at io.vertx.core.net.impl.SSLHelper.<init>(SSLHelper.java:199)
  | at io.vertx.core.net.impl.NetServerImpl.<init>(NetServerImpl.java:84)
  | at io.vertx.core.impl.VertxImpl.createNetServer(VertxImpl.java:265)
  | at io.vertx.mqtt.impl.MqttServerImpl.<init>(MqttServerImpl.java:52)
  | at io.vertx.mqtt.MqttServer.create(MqttServer.java:45)
  | at org.eclipse.hono.adapter.mqtt.AbstractVertxBasedMqttProtocolAdapter.bindMqttServer(AbstractVertxBasedMqttProtocolAdapter.java:255)
  | at org.eclipse.hono.adapter.mqtt.AbstractVertxBasedMqttProtocolAdapter.bindSecureMqttServer(AbstractVertxBasedMqttProtocolAdapter.java:221)
  | at org.eclipse.hono.adapter.mqtt.AbstractVertxBasedMqttProtocolAdapter.lambda$doStart$5(AbstractVertxBasedMqttProtocolAdapter.java:285)
  | at io.vertx.core.Future.lambda$compose$1(Future.java:265)
  | at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
  | at io.vertx.core.Future.compose(Future.java:261)
  | at org.eclipse.hono.adapter.mqtt.AbstractVertxBasedMqttProtocolAdapter.doStart(AbstractVertxBasedMqttProtocolAdapter.java:284)
  | at org.eclipse.hono.service.AbstractProtocolAdapterBase.startInternal(AbstractProtocolAdapterBase.java:360)
  | at org.eclipse.hono.service.AbstractServiceBase.start(AbstractServiceBase.java:92)
  | at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:494)
  | at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
  | at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
  | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.base/java.lang.Thread.run(Thread.java:834)
  | Caused by: java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSL
  | at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
  | at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
  | at java.base/java.lang.Class.forName0(Native Method)
  | at java.base/java.lang.Class.forName(Class.java:398)
  | at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:85)
  | at org.eclipse.hono.connection.impl.ConnectionFactoryImpl.addTlsTrustOptions(ConnectionFactoryImpl.java:301)
  | at org.eclipse.hono.connection.impl.ConnectionFactoryImpl.addOptions(ConnectionFactoryImpl.java:278)
  | at org.eclipse.hono.connection.impl.ConnectionFactoryImpl.connect(ConnectionFactoryImpl.java:129)
  | at org.eclipse.hono.connection.impl.ConnectionFactoryImpl.connect(ConnectionFactoryImpl.java:107)
  | at org.eclipse.hono.client.impl.HonoClientImpl.lambda$connect$5(HonoClientImpl.java:387)
  | at org.eclipse.hono.util.HonoProtonHelper.executeOrRunOnContext(HonoProtonHelper.java:180)
  | at org.eclipse.hono.client.impl.HonoClientImpl.executeOrRunOnContext(HonoClientImpl.java:226)
  | at org.eclipse.hono.client.impl.HonoClientImpl.connect(HonoClientImpl.java:375)
  | at org.eclipse.hono.client.impl.HonoClientImpl.connect(HonoClientImpl.java:360)
  | at org.eclipse.hono.client.impl.HonoClientImpl.connect(HonoClientImpl.java:345)
  | at org.eclipse.hono.service.AbstractProtocolAdapterBase.connectToService(AbstractProtocolAdapterBase.java:554)
  | at org.eclipse.hono.service.AbstractProtocolAdapterBase.connectToService(AbstractProtocolAdapterBase.java:526)
  | at org.eclipse.hono.service.AbstractProtocolAdapterBase.startInternal(AbstractProtocolAdapterBase.java:351)
  | ... 10 common frames omitted
```
I'm using the docker containers from docker hub and running on OKD with updated deploy script according to the one in 0.9.

**Comment by sophokles73** [comment]
is it possible that you have set the `nativeTlsRequired` property in your adapter configurations, e.g.
```
hono:
  mqtt:
    nativeTlsRequired: true
```

Hono does not ship *netty-tcnative* by default in its containers. You can add support for it using the *extension class path* described in the [admin guide](https://www.eclipse.org/hono/admin-guide/secure_communication/#using-openssl) or by creating your own images.

**Comment by BobClaerhout** [comment]
That was it!
Thanks for the quick and accurate response!
