### ISSUE TITLE
MQTT adapter doesn't start anymore

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#110]
When the MQTT adapter is starting up, it throws a NoClassDefFound exception because it requires `io.vertx.core.net.impl.NetServerBase` which is provided by vertx-core-3.3.4.Beta1 only. However, we are using vertx-core-3.3.3 ...

Here's the stack tracec:

15:43:34.851 [vert.x-eventloop-thread-2] ERROR o.e.h.a.m.Application$$EnhancerBySpringCGLIB$$5f2015e6 - could not start 'MQTT' adapter
java.lang.NoClassDefFoundError: io/vertx/core/net/impl/NetServerBase
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_102]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_102]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_102]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_102]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_102]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_102]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_102]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_102]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_102]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:89) ~[hono-adapter-mqtt-vertx-0.5-M5-SNAPSHOT.jar:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_102]
	at io.vertx.mqtt.MqttServer.create(MqttServer.java:45) ~[vertx-mqtt-server-3.4.0.Beta1.jar!/:na]
	at org.eclipse.hono.adapter.mqtt.VertxBasedMqttProtocolAdapter.bindMqttServer(VertxBasedMqttProtocolAdapter.java:88) ~[classes!/:na]
	at org.eclipse.hono.adapter.mqtt.VertxBasedMqttProtocolAdapter.start(VertxBasedMqttProtocolAdapter.java:130) ~[classes!/:na]
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434) ~[vertx-core-3.3.3.jar!/:na]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316) ~[vertx-core-3.3.3.jar!/:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
Caused by: java.lang.ClassNotFoundException: io.vertx.core.net.impl.NetServerBase
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_102]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_102]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:89) ~[hono-adapter-mqtt-vertx-0.5-M5-SNAPSHOT.jar:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_102]
	... 22 common frames omitted

**Comment by ppatierno** [comment]
Yes I forgot about this big change. Could we move to use the Vert.x Core 3.4.0.Beta1 ? The official 3.4.0 is pretty close ... I see some prepared blog post (not yet published) in the vert.x web site repo :-)

**Comment by sophokles73** [comment]
I guess you're lucky ;-) Since Vertx-core is an Eclipse project, we do not need a CQ in order to use it. The question is more: do we want to rely on a beta version. What's your take on this?

**Comment by ppatierno** [comment]
I don't want to be wrong for another time ... but the 3.4.0 release is very closed for what I can see :-)
If you want we can wait 2-3 more days (with the unresolved bug) and then I hope ... using the final 3.4.0 release :-D

**Comment by ppatierno** [comment]
@sophokles73 while we are chatting here the Vert.x 3.4.0 release is going to be announced. It's already in Maven Central. Can I update all the Vert.x versions (core, mqtt, ...) to 3.4.0 for Hono ?

**Comment by sophokles73** [comment]
We need to be careful not to break stuff. You can try to update vertx-core to 3.4.0 and see how you fare. Does everything build? Do the integration tests work? I can also do the same here and see if I find something strange. Once we conclude that an update seems to create no problems, you can commit the change.

WDYT?

**Comment by ppatierno** [comment]
You are absolutely right. After changing the mqtt version to 3.4.0.Beta1 I executed all the steps needed ... build and integration tests. It's clear we don't have integration tests with MQTT adapter ... that's something I have to provide :-)

**Comment by sophokles73** [comment]
vertx-core-3.4.0 depends on Netty 4.1.8 (instead of 4.1.5 as vertx-core-3.3.3 did). So you need to create a CQ for that. You will probably be able to piggy back an existing CQ for that version because the vertx guys will have had to create a CQ for that version themselves in order to be able to depend on it in their new release ...

**Comment by ppatierno** [comment]
Ok ... I'll do that ... in the meantime : 

http://vertx.io/blog/vert-x-3-4-0-is-released/

**Comment by sophokles73** [comment]
For your reference: [CQ12614 (Netty 4.1.8)](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12614) would probably be the one to piggy back ...

**Comment by sophokles73** [comment]
We can also try to stick with Netty 4.1.5 for the time being. Vertx 3.4.0 probably doesn't strictly *require* 4.1.8. This way we do not need to wait for your CQ to be resolved before we can upgrade to 3.4.0.

**Comment by ppatierno** [comment]
I asked to the Vert.x team about that. We will have problems without switching to Netty 4.1.8 (using Vert.x 3.4.0). They said me that Vert.x project has CQ for that. I'm not an expert about CQs. Do we need a specific Netty CQ for Eclipse Hono even if one of our dependency so Vert.x is an Eclipse project that already have a CQ for that ?

**Comment by sophokles73** [comment]
Yes, you'll need to create a CQ for Hono in which you refer to the existing CQ for Netty (which I have pointed out in my previous comment). This is called "piggy backing", i.e. you are merely indicating to the Eclipse IP team that we also want to use that lib so that they can create a records of that. This helps them to estimate the impact of a vulnerability/problem found in one of the dependencies.

**Comment by ppatierno** [comment]
Ah ok ... the CQ you pointed previously is exactly what the Vert.x team gave me :-)
So I'm going to open a CQ for Hono referring to this one and then updating Netty and Vert.x MQTT server in the Hono project.

**Comment by sophokles73** [comment]
You can only update and commit the change once the IP team has approved the piggy backing CQ.

**Comment by ppatierno** [comment]
Ok ... good to know thanks ;)

**Comment by ppatierno** [comment]
@sophokles73 here the CQ for that and waiting for approval before making changes on the source code : 
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12859

**Comment by ppatierno** [comment]
I'm going to close it on behalf of af2149863f5a746cc7282bb43741bd954b74df11
