### ISSUE TITLE
Using client credentials

### ISSUE THREAD

**Issue by BobClaerhout** [eclipse/hono#1135]
Hi,

I've been following the guid on https://blog.bosch-si.com/developer/x-509-based-device-authentication-in-eclipse-hono/. I have tried this both on the sandobx environment as well on my own environment.
When I try this in the sandbox environment I'm getting a 404.
When I try this in my own environment I'm getting a 401. When I have a look on the http-adpter logs, I'm getting following logging:

08:32:48.942 [vert.x-eventloop-thread-0] DEBUG o.e.h.adapter.http.X509AuthHandler - could not retrieve client certificate from request: {}
  | javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

As far as I can see, the device registry is not receiving any requests when I'm trying to send the message to the http adapter.

The stack trace of the peer not authenticated exception is the following:

```
08:40:25.958 [vert.x-eventloop-thread-0] DEBUG o.e.h.adapter.http.X509AuthHandler - could not retrieve client certificate from request: {}
--
  | javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
  | at java.base/sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:526)
  | at org.eclipse.hono.adapter.http.X509AuthHandler.parseCredentials(X509AuthHandler.java:78)
  | at io.vertx.ext.web.handler.impl.ChainAuthHandlerImpl.iterate(ChainAuthHandlerImpl.java:72)
  | at io.vertx.ext.web.handler.impl.ChainAuthHandlerImpl.parseCredentials(ChainAuthHandlerImpl.java:58)
  | at io.vertx.ext.web.handler.impl.AuthHandlerImpl.handle(AuthHandlerImpl.java:129)
  | at io.vertx.ext.web.handler.impl.AuthHandlerImpl.handle(AuthHandlerImpl.java:39)
  | at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:227)
  | at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121)
  | at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134)
  | at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:125)
  | at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:38)
  | at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:227)
  | at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121)
  | at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134)
  | at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:296)
  | at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:276)
  | at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:87)
  | at io.vertx.core.http.impl.HttpServerRequestImpl.doEnd(HttpServerRequestImpl.java:526)
  | at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:515)
  | at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:168)
  | at io.vertx.core.http.impl.Http1xServerConnection.handleContent(Http1xServerConnection.java:158)
  | at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:139)
  | at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:397)
  | at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
  | at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
  | at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
  | at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
  | at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
  | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1429)
  | at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
  | at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
  | at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
  | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
  | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
  | at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by sophokles73** [comment]
Can you disclose the tenant and device ID you are trying to connect with? I can then take a look at the sandbox's registry and check if the data you registered looks right.

**Comment by BobClaerhout** [comment]
I've retried this using the sandbox. I must have missed something, this is working now. (I used "ACMEaloxy" as the tenant and "hot-fuzz").
The question remains now about what is going on with my own installation.
Yesterday @b-abel and I came to the conclusion this might be an openshift issue. I'm looking into that. Due to maintenance, our test server is currently offline but should be back today.

**Comment by b-abel** [comment]
I just looked into the TLS debug log, you sent to @calohmn and it clearly shows that the adapter did not get the client certificate. The TLS setup is definitely specific for openshift, as the server certificate is issued by openshift. 
Maybe openshift terminates the TLS session? Did you stick to to the openshift deployment guide? 
@ctron Do you know if t is possible, that the standard deployment on openshift could lead to a situation where openshift terminates TLS?

**Comment by BobClaerhout** [comment]
Ok, finally made some progress.
The route towards the http adapter was configured with TLS termination "re-encrypt". I've changed this to "Passthrough". This allows the client certificate to be passed to the adapter.
Besides the fact I do have to tell curl to make an inscure request because of a self signed certificate I'm still getting an unauthorized error but the logging on the http adapter is different:


```
09:14:11.594 [vert.x-eventloop-thread-0] DEBUG o.e.h.s.a.ValidityOnlyTrustManagerFactory - accepting client certificate [not before: 2019-04-05T09:11:57Z, not after: 2020-04-04T09:11:57Z, issuer DN: CN=Sensors,O=ACMEaloxy Inc.]
--
  | 09:14:11.643 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.HonoClientImpl - reusing existing client [target: tenant]
  | 09:14:11.648 [vert.x-eventloop-thread-0] DEBUG o.e.h.s.a.d.DeviceCertificateValidator - validation of device certificate [subject DN: CN=Hot Fuzz Device,O=ACMEaloxy Inc.] failed
  | java.security.cert.CertPathValidatorException: signature check failed
  | at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
  | at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233)
  | at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141)
  | at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)
  | at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
  | at org.eclipse.hono.service.auth.device.DeviceCertificateValidator.validate(DeviceCertificateValidator.java:65)
  | at org.eclipse.hono.service.auth.device.TenantServiceBasedX509Authentication.lambda$validateClientCertificate$1(TenantServiceBasedX509Authentication.java:163)
  | at io.vertx.core.Future.lambda$compose$1(Future.java:265)
  | at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
  | at io.vertx.core.Future.compose(Future.java:261)
  | at org.eclipse.hono.service.auth.device.TenantServiceBasedX509Authentication.lambda$validateClientCertificate$3(TenantServiceBasedX509Authentication.java:159)
  | at io.vertx.core.Future.lambda$compose$1(Future.java:265)
  | at io.vertx.core.impl.SucceededFuture.setHandler(SucceededFuture.java:40)
  | at io.vertx.core.Future.compose(Future.java:261)
  | at org.eclipse.hono.service.auth.device.TenantServiceBasedX509Authentication.validateClientCertificate(TenantServiceBasedX509Authentication.java:148)
  | at org.eclipse.hono.adapter.http.X509AuthHandler.parseCredentials(X509AuthHandler.java:81)
  | at io.vertx.ext.web.handler.impl.ChainAuthHandlerImpl.iterate(ChainAuthHandlerImpl.java:72)
  | at io.vertx.ext.web.handler.impl.ChainAuthHandlerImpl.parseCredentials(ChainAuthHandlerImpl.java:58)
  | at io.vertx.ext.web.handler.impl.AuthHandlerImpl.handle(AuthHandlerImpl.java:129)
  | at io.vertx.ext.web.handler.impl.AuthHandlerImpl.handle(AuthHandlerImpl.java:39)
  | at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:227)
  | at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121)
  | at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134)
  | at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:125)
  | at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:38)
  | at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:227)
  | at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121)
  | at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134)
  | at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:296)
  | at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:276)
  | at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:87)
  | at io.vertx.core.http.impl.HttpServerRequestImpl.doEnd(HttpServerRequestImpl.java:526)
  | at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:515)
  | at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:168)
  | at io.vertx.core.http.impl.Http1xServerConnection.handleContent(Http1xServerConnection.java:158)
  | at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:139)
  | at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:397)
  | at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
  | at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
  | at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
  | at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
  | at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
  | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1429)
  | at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
  | at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
  | at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
  | at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
  | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
  | at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.base/java.lang.Thread.run(Thread.java:834)
  | Caused by: java.security.SignatureException: Signature does not match.
  | at java.base/sun.security.x509.X509CertImpl.verify(X509CertImpl.java:423)
  | at java.base/sun.security.provider.certpath.BasicChecker.verifySignature(BasicChecker.java:166)
  | at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:147)
  | at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
  | ... 78 common frames omitted
  | 09:14:11.648 [vert.x-eventloop-thread-0] DEBUG o.e.h.s.a.d.TenantServiceBasedX509Authentication - verification of client certificate failed: Error Code: 401


```

**Comment by BobClaerhout** [comment]
Huge thank you to @b-abel for the assistance so far! After some debugging we discovered the certificates created the way presented on https://blog.bosch-si.com/developer/x-509-based-device-authentication-in-eclipse-hono/ do not work. When using the example certificates, the verification of the certificate works.
Important difference: the certificates work against the sandbox environment but not against my own.
Next step is adapting the "create_certs.sh" script to create new certs and use them.

**Comment by sophokles73** [comment]
@BobClaerhout is this still an issue or can you close it?

**Comment by BobClaerhout** [comment]
I didn't create my own certificates using the example scripts yet.
I consider this fixed however and will certainly test this again later. I will create another issue or re-open this one if needed.
