### ISSUE TITLE
Issue with command & control -> Micrometer + Prometheus -> causing duplicate dispositions

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#1149]
When doing some tests with command and control in Hono 0.9, I ran into the following issue:

~~~
java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'hono_messages_received_seconds' containing tag keys [component_name, component_type, host, qos, status, tenant, type]. The meter you are attempting to register has keys [component_name, component_type, host, qos, status, tenant, ttd, type].
~~~

<details>

<summary>Full exception stack trace</summary>

~~~
2019-04-08T11:05:11.997Z DEBUG [VertxBasedHttpProtocolAdapter] cannot process [TELEMETRY] message from device [tenantId: iot-project-ns.shared-iot-project, deviceId: b4371722-5d19-44c6-85ce-a82b9d5b3260]
java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'hono_messages_received_seconds' containing tag keys [component_name, component_type, host, qos, status, tenant, type]. The meter you are attempting to register has keys [component_name, component_type, host, qos, status, tenant, ttd, type].
	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$collectorByName$9(PrometheusMeterRegistry.java:360)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932)
	at io.micrometer.prometheus.PrometheusMeterRegistry.collectorByName(PrometheusMeterRegistry.java:347)
	at io.micrometer.prometheus.PrometheusMeterRegistry.newTimer(PrometheusMeterRegistry.java:160)
	at io.micrometer.core.instrument.MeterRegistry.lambda$timer$2(MeterRegistry.java:258)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:567)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:529)
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:256)
	at io.micrometer.core.instrument.Timer$Builder.register(Timer.java:447)
	at io.micrometer.core.instrument.MeterRegistry.timer(MeterRegistry.java:383)
	at org.eclipse.hono.service.metric.MicrometerBasedMetrics.reportTelemetry(MicrometerBasedMetrics.java:176)
	at org.eclipse.hono.adapter.http.AbstractVertxBasedHttpProtocolAdapter.lambda$doUploadMessage$19(AbstractVertxBasedHttpProtocolAdapter.java:687)
	at io.vertx.ext.web.impl.RoutingContextImpl.lambda$null$2(RoutingContextImpl.java:461)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.vertx.ext.web.impl.RoutingContextImpl.lambda$getBodyEndHandlers$3(RoutingContextImpl.java:461)
	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:343)
	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:367)
	at org.eclipse.hono.adapter.http.AbstractVertxBasedHttpProtocolAdapter.lambda$doUploadMessage$22(AbstractVertxBasedHttpProtocolAdapter.java:723)
	at io.vertx.core.Future.lambda$map$2(Future.java:301)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86)
	at io.vertx.core.Future.lambda$recover$4(Future.java:383)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:151)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86)
	at io.vertx.core.Future.lambda$map$2(Future.java:306)
	at io.vertx.core.impl.CompositeFutureImpl.lambda$all$1(CompositeFutureImpl.java:49)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:132)
	at org.eclipse.hono.adapter.http.AbstractVertxBasedHttpProtocolAdapter.lambda$createCommandConsumer$26(AbstractVertxBasedHttpProtocolAdapter.java:886)
	at org.eclipse.hono.client.CommandConsumer.lambda$create$0(CommandConsumer.java:151)
	at org.eclipse.hono.client.impl.AbstractHonoClient.lambda$createReceiver$8(AbstractHonoClient.java:394)
	at io.vertx.proton.impl.ProtonReceiverImpl.onDelivery(ProtonReceiverImpl.java:206)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:163)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:392)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:225)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:123)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:370)
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:397)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:834)
~~~

</details>

**Comment by ctron** [comment]
This also causes duplicate dispositions to get sent out.

The first one goes out, as the command is properly handled:

https://github.com/eclipse/hono/blob/3f8f7a483824459100159fcad014e371ca545a0e/adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java#L678-L680

Then it fails to report to micrometer a few lines below:

https://github.com/eclipse/hono/blob/3f8f7a483824459100159fcad014e371ca545a0e/adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java#L687

Then the second one goes out in the recover section:

https://github.com/eclipse/hono/blob/3f8f7a483824459100159fcad014e371ca545a0e/adapters/http-vertx-base/src/main/java/org/eclipse/hono/adapter/http/AbstractVertxBasedHttpProtocolAdapter.java#L730-L735

**Comment by sophokles73** [comment]
The way I understand it, Prometheus doesn't like the fact that we omit the TTD tag when reporting telemetry in the HTTP adapter for requests that do not contain the `ttd` header/param. IIRC we discussed some time ago whether to always include e.g. `Ttd.NONE` in this case or to omit the tag altogether ... ;-)

Seems like we need to always include a value for these *optional* tags after all ...
