### ISSUE TITLE
Artemis replaced by Enmasse

### ISSUE THREAD

**Issue by alexju88** [eclipse/hono#1186]
Hi guys,
We are now using the default settings of Hono with Artemis, but we want to try Enmasse, so could any experts tell me how to integrated Enmasse instead of Artemis ? Any links or documents ?

I found a guide here: https://github.com/dejanb/hono/blob/enmasse/site/content/deployment/enmasse.md , but it was 2 years ago version, it's too old. And We need to use helm to install Hono. So this guide does not help too much.

Do we still need to deploy "hono-dispatch-router" if we use Enmasse ? In my understanding, we don't need. We removed artemis and hono-dispatch-router from deployment.

Thank you very much!

**Comment by alexju88** [comment]
PS: Enmasse has already online in our Cloud environment.

**Comment by alexju88** [comment]
**The Enmasse logs:**

2019-04-23 02:20:09.760796 +0000 SERVER (info) enabling remote authentication service standard-authservice:5671
2019-04-23 02:20:09.761261 +0000 SERVER (info) [C390] Accepted connection to 0.0.0.0:5672 from 10.0.0.161:59876
2019-04-23 02:20:09.761294 +0000 SERVER (info) enabling remote authentication service standard-authservice:5671
2019-04-23 02:20:09.761624 +0000 SERVER (info) [C391] Accepted connection to 0.0.0.0:5672 from 10.0.0.161:59874
2019-04-23 02:20:09.764461 +0000 AUTHSERVICE (warning) Downstream disconnected: proton:io Name or service not known - connect to  standard-authservice:5671
2019-04-23 02:20:09.764495 +0000 SERVER (info) [C391] Connection from 10.0.0.161:59874 (to 0.0.0.0:5672) failed: amqp:unauthorized-access Failed to authenticate client [mech=none]
2019-04-23 02:20:09.764522 +0000 AUTHSERVICE (warning) Downstream disconnected: proton:io Name or service not known - connect to  standard-authservice:5671
2019-04-23 02:20:09.764550 +0000 SERVER (info) [C390] Connection from 10.0.0.161:59876 (to 0.0.0.0:5672) failed: amqp:unauthorized-access Failed to authenticate client [mech=none]

**Comment by alexju88** [comment]
**http-adapter logs:**

02:09:05.020 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - can't connect to AMQP 1.0 container [amqp://messaging-lfty1uyygv.hono-test:5672]: Disconnected
02:09:05.021 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.HonoClientImpl - connection attempt failed
io.vertx.core.VertxException: Disconnected
	at io.vertx.proton.impl.ProtonClientImpl.lambda$null$0(ProtonClientImpl.java:81)
	at io.vertx.proton.impl.ProtonConnectionImpl.fireDisconnect(ProtonConnectionImpl.java:381)
	at io.vertx.proton.impl.ProtonTransport.handleSocketEnd(ProtonTransport.java:94)
	at io.vertx.core.net.impl.NetSocketImpl.checkEnd(NetSocketImpl.java:365)
	at io.vertx.core.net.impl.NetSocketImpl.handleClosed(NetSocketImpl.java:351)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelInactive$5(VertxHandler.java:164)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:164)^C
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
02:09:05.521 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.HonoClientImpl - starting attempt [#729] to connect to server [messaging-lfty1uyygv.hono-test:5672]
02:09:05.521 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connecting to AMQP 1.0 container [amqp://messaging-lfty1uyygv.hono-test:5672]
02:09:05.521 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.HonoClientImpl - starting attempt [#719] to connect to server [messaging-lfty1uyygv.hono-test:5672]
02:09:05.522 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connecting to AMQP 1.0 container [amqp://messaging-lfty1uyygv.hono-test:5672]
02:09:05.526 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - can't connect to AMQP 1.0 container [amqp://messaging-lfty1uyygv.hono-test:5672]: Disconnected

**Comment by alexju88** [comment]
it seems that we didn't set username+password+Authenticate mechanism of Enmasse for HTTP-Adapter, but we can't find where to configure it....

**Comment by sophokles73** [comment]
@alexju88 

what's the status of this? did you work out your issues?

**Comment by alexju88** [comment]
> @alexju88
> 
> what's the status of this? did you work out your issues?

No, I haven't, I don't know how to configure username & password for Hono, in order to connect with enmasse. Could you tell me how ?

**Comment by sophokles73** [comment]
> Do we still need to deploy "hono-dispatch-router" if we use Enmasse ? In my understanding, we don't need. We removed artemis and hono-dispatch-router from deployment.

No, you do not need them when using enMasse.

@ctron can you help out Alex?

**Comment by sophokles73** [comment]
@calohmn any thoughts on this?

**Comment by calohmn** [comment]
> I don't know how to configure username & password for Hono, in order to connect with enmasse. Could you tell me how ?

(Prerequisite for the following is that you have deployed the EnMasse standard authentication service.)
First you have to create a user in EnMasse. See the [EnMasse docs](https://enmasse.io/documentation/0.27.2/kubernetes/#managing-users-messaging) for that. To configure this user with send/receive rights for all addresses, you can use
````
  authorization:
    - addresses: ["*"]
      operations: ["send", "recv", "manage"]
````
in the user definition yaml (the `manage` operation gives this user also access to the [EnMasse console](https://enmasse.io/documentation/0.27.2/kubernetes/#assembly-using-console-messaging)).

The user name and password of the created user should then be configured in the Hono protocol adapter config (e.g. `hono-adapter-http-vertx-config.yaml`). Put them in `hono.messaging.username` and `hono.messaging.password`.

**Comment by alexju88** [comment]
> 
> 
> > I don't know how to configure username & password for Hono, in order to connect with enmasse. Could you tell me how ?
> 
> (Prerequisite for the following is that you have deployed the EnMasse standard authentication service.)
> First you have to create a user in EnMasse. See the [EnMasse docs](https://enmasse.io/documentation/0.27.2/kubernetes/#managing-users-messaging) for that. To configure this user with send/receive rights for all addresses, you can use
> 
> ```
>   authorization:
>     - addresses: ["*"]
>       operations: ["send", "recv", "manage"]
> ```
> 
> in the user definition yaml (the `manage` operation gives this user also access to the [EnMasse console](https://enmasse.io/documentation/0.27.2/kubernetes/#assembly-using-console-messaging)).
> 
> The user name and password of the created user should then be configured in the Hono protocol adapter config (e.g. `hono-adapter-http-vertx-config.yaml`). Put them in `hono.messaging.username` and `hono.messaging.password`.

Hi Lohmann, 
thanks for your kind help!

For the Enmasse, we have already deployed Enmasse in the same namespace with Hono before and have tested its function to be OK. Enmasse user has already been created, just like what you said as above.

For the Hono side, I checked the file "hono-adapter-http-vertx-config.yml" (there is no *.**yaml** file) , currently there is no available place to configure the key "hono.messaging.username" and "hono.messaging.password",  file content is as below:

_hono:
  app:
    maxInstances: 1
    healthCheckPort: 8088
    healthCheckBindAddress: 0.0.0.0
  http:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: /etc/hono/http-adapter-key.pem
    certPath: /etc/hono/http-adapter-cert.pem
  **messaging:
    name: 'Hono HTTP Adapter'
    host: messaging-0xi8553fe8.hono-test
    port: 5672**
  registration:
    name: 'Hono HTTP Adapter'
    host: hono-service-device-registry.hono-test
    port: 5671
    credentialsPath: /etc/hono/http-adapter.credentials
    trustStorePath: /etc/hono/trusted-certs.pem
  credentials:
    name: 'Hono HTTP Adapter'
    host: hono-service-device-registry.hono-test
    port: 5671
    credentialsPath: /etc/hono/http-adapter.credentials
    trustStorePath: /etc/hono/trusted-certs.pem
  tenant:
    name: 'Hono HTTP Adapter'
    host: hono-service-device-registry.hono-test
    port: 5671
    credentialsPath: /etc/hono/http-adapter.credentials
    trustStorePath: /etc/hono/trusted-certs.pem
  command:
    name: 'Hono HTTP Adapter'
    host: messaging-0xi8553fe8.hono-test
    port: 5672_


So I try to add environment variables into the file "helm/templates/hono-adapter-http/hono-adapter-http-vertx-deployment.yml" as below, I tried with two different names:

----
        - name: HONO_MESSAGING_USERNAME
          value: hono 
        - name: HONO_MESSAGING_PASSWORD
          value: hono_iot_2019
        - name: hono.messaging.username
          value: hono
        - name: hono.messaging.password
          value: hono_iot_2019
----

But still we meet errors in the log of POD hono-adapter-http-vertx:

----
_05:51:11.045 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - can't connect to AMQP 1.0 container [amqp://messaging-0xi8553fe8.hono-test:5672]: Could not find a suitable SASL mechanism for the remote peer using the available credentials.
05:51:11.047 [vert.x-eventloop-thread-0] INFO  o.e.hono.client.impl.HonoClientImpl - stopping connection attempt to server [host: messaging-0xi8553fe8.hono-test, port: 5672] due to terminal error
io.vertx.proton.sasl.SaslSystemException: Could not find a suitable SASL mechanism for the remote peer using the available credentials.
	at io.vertx.proton.impl.ProtonSaslClientAuthenticatorImpl.handleSaslInit(ProtonSaslClientAuthenticatorImpl.java:141)
	at io.vertx.proton.impl.ProtonSaslClientAuthenticatorImpl.process(ProtonSaslClientAuthenticatorImpl.java:92)
	at io.vertx.proton.impl.ProtonTransport.processSaslAuthentication(ProtonTransport.java:211)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:194)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:392)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:225)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:123)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:370)
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:397)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
05:51:11.048 [vert.x-eventloop-thread-0] WARN  o.e.h.a.h.v.VertxBasedHttpProtocolAdapter - failed to connect to Command and Control service
org.eclipse.hono.client.ClientErrorException: no suitable SASL mechanism found for authentication with server
	at org.eclipse.hono.client.impl.HonoClientImpl.failConnectionAttempt(HonoClientImpl.java:545)
	at org.eclipse.hono.client.impl.HonoClientImpl.lambda$connect$4(HonoClientImpl.java:395)
	at org.eclipse.hono.connection.impl.ConnectionFactoryImpl.failConnectionAttempt(ConnectionFactoryImpl.java:159)
	at org.eclipse.hono.connection.impl.ConnectionFactoryImpl.handleConnectionAttemptResult(ConnectionFactoryImpl.java:180)
	at org.eclipse.hono.connection.impl.ConnectionFactoryImpl.lambda$connect$1(ConnectionFactoryImpl.java:151)
	at io.vertx.proton.impl.ProtonClientImpl$ConnectCompletionHandler.handle(ProtonClientImpl.java:123)
	at io.vertx.proton.impl.ProtonClientImpl$ConnectCompletionHandler.handle(ProtonClientImpl.java:103)
	at io.vertx.proton.impl.ProtonSaslClientAuthenticatorImpl.process(ProtonSaslClientAuthenticatorImpl.java:114)
	at io.vertx.proton.impl.ProtonTransport.processSaslAuthentication(ProtonTransport.java:211)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:194)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:392)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:225)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:123)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:370)
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:397)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
05:51:11.117 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connected to AMQP 1.0 container [amqp://messaging-0xi8553fe8.hono-test:5672], opening connection ...
05:51:11.124 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connection to container [qdrouterd-0xi8553fe8-1] at [amqp://messaging-0xi8553fe8.hono-test:5672] open
05:51:11.125 [vert.x-eventloop-thread-0] INFO  o.e.h.a.h.v.VertxBasedHttpProtocolAdapter - connected to AMQP Messaging Network
05:51:11.159 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connected to AMQP 1.0 container [amqps://hono-service-device-registry.hono-test:5671], opening connection ...
05:51:11.162 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connection to container [hono-registry-0.0.0.0:5671] at [amqps://hono-service-device-registry.hono-test:5671] open
05:51:11.163 [vert.x-eventloop-thread-0] INFO  o.e.h.a.h.v.VertxBasedHttpProtocolAdapter - connected to Credentials service
05:51:11.175 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connected to AMQP 1.0 container [amqps://hono-service-device-registry.hono-test:5671], opening connection ...
05:51:11.178 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connection to container [hono-registry-0.0.0.0:5671] at [amqps://hono-service-device-registry.hono-test:5671] open
05:51:11.178 [vert.x-eventloop-thread-0] INFO  o.e.h.a.h.v.VertxBasedHttpProtocolAdapter - connected to Tenant service
05:51:11.185 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connected to AMQP 1.0 container [amqps://hono-service-device-registry.hono-test:5671], opening connection ...
05:51:11.188 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connection to container [hono-registry-0.0.0.0:5671] at [amqps://hono-service-device-registry.hono-test:5671] open
05:51:11.188 [vert.x-eventloop-thread-0] INFO  o.e.h.a.h.v.VertxBasedHttpProtocolAdapter - connected to Device Registration service_
----


There are two items in above message which are very interesting:
----
_05:51:11.047 [vert.x-eventloop-thread-0] INFO  o.e.hono.client.impl.HonoClientImpl - stopping connection attempt to server [host: messaging-0xi8553fe8.hono-test, port: 5672] due to terminal error
io.vertx.proton.sasl.SaslSystemException: Could not find a suitable SASL mechanism for the remote peer using the available credentials.

05:51:11.125 [vert.x-eventloop-thread-0] INFO  o.e.h.a.h.v.VertxBasedHttpProtocolAdapter - connected to AMQP Messaging Network_
----



Does this mean that http adapter has connected with Enmasse successfully? 

If so, why the pod status is not running and the port 8080 is not listening ?

**Comment by alexju88** [comment]
Hi @calohmn , my Hono helm folder is as here : https://github.com/alexju88/hono-enmasse
You could help me check any problem about configurations.
Appreciate!

**Comment by calohmn** [comment]
@alexju88 By "hono.messaging.username" I meant putting the "username" entry in the yaml structure below "hono" and "messaging", like this:
````
hono:
  app:
    maxInstances: 1
    healthCheckPort: 8088
    healthCheckBindAddress: 0.0.0.0
  http:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: /etc/hono/http-adapter-key.pem
    certPath: /etc/hono/http-adapter-cert.pem
  messaging:
    name: 'Hono HTTP Adapter'
    host: messaging-0xi8553fe8.hono-test
    port: 5672
    username: myUser 
    password: myPassword
````

**Comment by alexju88** [comment]
> 
> 
> @alexju88 By "hono.messaging.username" I meant putting the "username" entry in the yaml structure below "hono" and "messaging", like this:
> 
> ```
> hono:
>   app:
>     maxInstances: 1
>     healthCheckPort: 8088
>     healthCheckBindAddress: 0.0.0.0
>   http:
>     bindAddress: 0.0.0.0
>     insecurePortBindAddress: 0.0.0.0
>     insecurePortEnabled: true
>     keyPath: /etc/hono/http-adapter-key.pem
>     certPath: /etc/hono/http-adapter-cert.pem
>   messaging:
>     name: 'Hono HTTP Adapter'
>     host: messaging-0xi8553fe8.hono-test
>     port: 5672
>     username: myUser 
>     password: myPassword
> ```


Hi, I tried as above, but comes with SASL mechanism not found problem :


06:37:34.410 [vert.x-eventloop-thread-0] WARN  o.e.h.a.h.v.VertxBasedHttpProtocolAdapter - failed to connect to Command and Control service
org.eclipse.hono.client.ClientErrorException: no suitable SASL mechanism found for authentication with server


Should we tell Hono to use a mechanism like PLAIN ?

**Comment by calohmn** [comment]
> VertxBasedHttpProtocolAdapter - failed to connect to Command and Control service

This points to an issue concerning the Command & Control related configuration. 
Put the EnMasse username/password also below the "command" entry in the config yaml:
````
hono:
[...]
  command:
    name: 'Hono HTTP Adapter'
    host: messaging-0xi8553fe8.hono-test
    port: 5672
    username: myUser 
    password: myPassword
````

**Comment by alexju88** [comment]
> 
> 
> > VertxBasedHttpProtocolAdapter - failed to connect to Command and Control service
> 
> This points to an issue concerning the Command & Control related configuration.
> Put the EnMasse username/password also below the "command" entry in the config yaml:
> 
> ```
> hono:
> [...]
>   command:
>     name: 'Hono HTTP Adapter'
>     host: messaging-0xi8553fe8.hono-test
>     port: 5672
>     username: myUser 
>     password: myPassword
> ```

Thanks Carsten, it works!

**Comment by sophokles73** [comment]
@alexju88 can you please close this issue if your problems have been resolved?

**Comment by alexju88** [comment]
Just know this function, sorry..I'm a new github user.
