### ISSUE TITLE
Error running CoAP integration tests ("Invalid argument")

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1345]
When running the Hono integration tests using the minikube VM as docker host, the CoAP tests fail with such an error:
````
[INFO] Running org.eclipse.hono.tests.coap.TelemetryCoapIT
QPID2019-07-10 15:21:12.706740 +0000 SERVER (info) enabling remote authentication service hono-service-auth.hono:5672
QPID2019-07-10 15:21:12.706791 +0000 SERVER (info) [C32] Accepted connection to 0.0.0.0:5672 from 192.168.99.1:32856
17:21:12.756 [vert.x-eventloop-thread-0] INFO  o.e.h.tests.IntegrationTestSupport - connected to AMQP Messaging Network [192.168.99.100:32779]
17:21:12.764 [Time-limited test] INFO  o.e.hono.tests.coap.TelemetryCoapIT - running testUploadUsingQoS1
17:21:12.764 [Time-limited test] INFO  o.e.hono.tests.coap.TelemetryCoapIT - using CoAP adapter [host: 192.168.99.100, coap port: 32769, coaps port: 32768]
QPID2019-07-10 15:21:12.743687 +0000 ROUTER (info) [C1][L3222] Link detached: del=0 presett=0 psdrop=0 acc=0 rej=0 rel=0 mod=0 delay1=0 delay10=0
QPID2019-07-10 15:21:12.743745 +0000 ROUTER (info) [C1][L3224] Link detached: del=0 presett=0 psdrop=0 acc=0 rej=0 rel=0 mod=0 delay1=0 delay10=0
QPID2019-07-10 15:21:12.743760 +0000 ROUTER (info) [C1][L3226] Link detached: del=60 presett=0 psdrop=0 acc=60 rej=0 rel=0 mod=0 delay1=0 delay10=0
QPID2019-07-10 15:21:12.751251 +0000 AUTHSERVICE (info) authenticated as consumer@HONO
QPID2019-07-10 15:21:12.755738 +0000 ROUTER (info) [C32] Connection Opened: dir=in host=192.168.99.1:32856 vhost= encrypted=no auth=PLAIN user=consumer@HONO container_id=null-c6def17b-4dd8-4b85-952b-361936cce3f2 props={:product="vertx-proton", :version="3.7.1"}
17:21:12.872 [DTLS-Connection-Handler-2] WARN  o.e.c.scandium.DTLSConnector - Could not send record
java.io.IOException: Invalid argument
	at java.base/java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.base/java.net.DatagramSocket.send(DatagramSocket.java:695)
	at org.eclipse.californium.scandium.DTLSConnector.sendNextDatagramOverNetwork(DTLSConnector.java:1959)
	at org.eclipse.californium.scandium.DTLSConnector.sendFlightOverNetwork(DTLSConnector.java:1945)
	at org.eclipse.californium.scandium.DTLSConnector.sendFlight(DTLSConnector.java:1903)
	at org.eclipse.californium.scandium.dtls.Handshaker.sendFlight(Handshaker.java:999)
	at org.eclipse.californium.scandium.dtls.ClientHandshaker.startHandshake(ClientHandshaker.java:709)
	at org.eclipse.californium.scandium.DTLSConnector.sendMessage(DTLSConnector.java:1768)
	at org.eclipse.californium.scandium.DTLSConnector.access$1100(DTLSConnector.java:205)
	at org.eclipse.californium.scandium.DTLSConnector$10.run(DTLSConnector.java:1705)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:277)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
````

**Comment by calohmn** [comment]
The error also occurs when running the tests with `mvn verify -Prun-tests -Djava.net.preferIPv4Stack=true -Dit.test=TelemetryCoapIT`.

**Comment by sophokles73** [comment]
Running `mvn verify -Prun-tests -Djava.net.preferIPv4Stack=true -Dit.test=TelemetryCoapIT` with a local Docker daemon on my Linux laptop succeeds. Does this only occur when using a *remote* Docker daemon or does it also fail on your machine when you use a local Docker daemon?

**Comment by calohmn** [comment]
IIRC it worked when using a local Docker daemon.
I also get the error when using a remote Docker daemon with dockermachine.

**Comment by sophokles73** [comment]
@calohmn is this still an issue? And, more importantly, is this really an issue at all, i.e. is running the integration tests using a minikube's Docker daemon an important use case?

**Comment by calohmn** [comment]
@sophokles73 I think for the Hono development environment, being able to use the same docker host for integration tests and the Hono helm deployment is quite beneficial. And using minikube there looks straightforward. Therefore it would be good to get this fixed.

**Comment by boaks** [comment]
@calohmn 

Does this till occur? 
I use microk8s and it didn't happen on "my machine".

**Comment by calohmn** [comment]
> Does this till occur?

Yes. I mostly run the integration tests with a local docker daemon now - there it works. But using the docker damon of a running minikube - even with the `docker` driver (ie. without an extra VM) - there is still the above error.

**Comment by fkaltner** [comment]
@calohmn:

together with @boaks, I think I found a solution to this problem. At least this change made the tests running on macOS. I created pull request so that you can test on your machine.

**Comment by sophokles73** [comment]
@calohmn can this be closed?
