### ISSUE TITLE
Hono does not start on Openshift

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#165]
Hono-app crashes on Openshift with output: 
`14:11:25.823 [vert.x-eventloop-thread-0] ERROR o.e.h.a.i.InMemoryAuthorizationService - cannot load permissions from resource URL [file:/etc/hono/permissions.json]
java.io.FileNotFoundException: permissions resource does not exist
	at org.eclipse.hono.authorization.impl.InMemoryAuthorizationService.loadPermissions(InMemoryAuthorizationService.java:147) ~[hono-server-0.5-M6-SNAPSHOT.jar!/:0.5-M6-SNAPSHOT]
	at org.eclipse.hono.authorization.impl.InMemoryAuthorizationService.doStart(InMemoryAuthorizationService.java:72) ~[hono-server-0.5-M6-SNAPSHOT.jar!/:0.5-M6-SNAPSHOT]
	at org.eclipse.hono.authorization.impl.BaseAuthorizationService.start(BaseAuthorizationService.java:66) [hono-server-0.5-M6-SNAPSHOT.jar!/:0.5-M6-SNAPSHOT]
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434) [vertx-core-3.4.1.jar!/:na]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337) ~[vertx-core-3.4.1.jar!/:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]`

The file `/etc/hono/permissions.json` is not present in the container by default.

**Comment by ppatierno** [comment]
The permissions.json file is created by the Hono component on startup on the persistent volume. Did you follow the guide here ? https://www.eclipse.org/hono/deployment/openshift/
Or are you using the "one script" deployment and there is something missing there ?

**Comment by b-abel** [comment]
I only did 
`
$ mvn clean install -Pbuild-docker-image 
$ cd example/openshift/
$ bash openshift_deploy.sh
`

**Comment by ppatierno** [comment]
I see the persistent volume creation in the script. Can you try the step by step way please ?

**Comment by ppatierno** [comment]
It's fixed now 7d2e343d58951b3f597adfdeaef1571d4b99932b

**Comment by b-abel** [comment]
Great! Thank you for your your quick response. That was the fix I wanted to propose. Sorry, I got interrupted yesterday and could not proceed.
