### ISSUE TITLE
Does Eclipse Hono support a NodeJS Client for telemetry consumption and sending commands?

### ISSUE THREAD

**Issue by kakaly** [eclipse/hono#1667]
I am using the 'rhea' nodejs library to create a AMQP client. I have a local instance of HONO running and the Java CLI client successfully receives messages when I publish messages to hono. But, when I run the following code:

```
var container = require('rhea');
container.on('message', function (context) {
    console.log(context.message.body);
    context.connection.close();
});
container.once('sendable', function (context) {
    context.sender.send({body:'Hello World!'});
});
var connection = container.connect({'host':'xx.xx.xx.xx', 'port':15672, 'username': 'consumer@HONO', 'password': 'verysecret'});
connection.open_receiver('/telemetry');
connection.open_sender('/telemetry');
```

I receive the following response:

```

events.js:187
      throw er; // Unhandled 'error' event
      ^
<ref *1> LinkError: link disallowed by local policy
    at Receiver.link.on_detach (/home/teuser/rhea/node_modules/rhea/lib/link.js:165:86)
    at Session.on_detach (/home/teuser/rhea/node_modules/rhea/lib/session.js:730:27)
    at Connection.<computed> [as on_detach] (/home/teuser/rhea/node_modules/rhea/lib/connection.js:785:30)
    at c.dispatch (/home/teuser/rhea/node_modules/rhea/lib/types.js:910:33)
    at Transport.read (/home/teuser/rhea/node_modules/rhea/lib/transport.js:109:36)
    at SaslClient.read (/home/teuser/rhea/node_modules/rhea/lib/sasl.js:324:26)
    at Connection.input (/home/teuser/rhea/node_modules/rhea/lib/connection.js:519:35)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:326:12)
    at readableAddChunk (_stream_readable.js:301:11)
Emitted 'error' event on Container instance at:
    at Container.dispatch (/home/teuser/rhea/node_modules/rhea/lib/container.js:41:33)
    at Connection.dispatch (/home/teuser/rhea/node_modules/rhea/lib/connection.js:247:40)
    at Connection.input (/home/teuser/rhea/node_modules/rhea/lib/connection.js:537:18)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:326:12)
    at readableAddChunk (_stream_readable.js:301:11)
    at Socket.Readable.push (_stream_readable.js:235:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  message: 'link disallowed by local policy',
  condition: 'amqp:unauthorized-access',
  description: 'link disallowed by local policy',
  link: Receiver {
    session: Session {
      connection: [Connection],
      outgoing: [Outgoing],
      incoming: [Incoming],
      state: [EndpointState],
      local: [Object],
      remote: [Object],
      links: [Object],
      options: {},
      observers: [EventEmitter]
    },
    connection: Connection {
      options: [Object],
      container: [Container],
      registered: true,
      state: [EndpointState],
      local_channel_map: [Object],
      remote_channel_map: [Object],
      local: [Object],
      remote: [Object],
      session_policy: [Object],
      amqp_transport: [Transport],
      sasl_transport: [SaslClient],
      transport: [SaslClient],
      conn_established_counter: 1,
      heartbeat_out: undefined,
      heartbeat_in: undefined,
      abort_idle: false,
      socket_ready: true,
      scheduled_reconnect: undefined,
      default_sender: undefined,
      closed_with_non_fatal_error: false,
      is_server: false,
      socket: [Socket],
      saved_error: [Circular *1]
    },
    name: '3efb33f0-9c9f-ef49-b4ea-05cff97596e7',
    options: {
      source: [Object],
      name: '3efb33f0-9c9f-ef49-b4ea-05cff97596e7',
      target: undefined
    },
    state: EndpointState {
      local_open: true,
      remote_open: false,
      open_requests: 0,
      close_requests: 0,
      initialised: true,
      marker: undefined
    },
    issue_flow: true,
    local: { handle: 0, attach: [c], detach: [c] },
    remote: { handle: undefined, attach: [c], detach: [c] },
    delivery_count: 0,
    credit: 1000,
    observers: EventEmitter {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined
    },
    drain: false
  }
}
```

I haven't been able to figure out what is going on.

**Comment by sophokles73** [comment]
It looks like you are trying to send telemetry data using the same connection that you use to receive it.
The source of telemetry data and events are devices which connect to one of Hono's protocol adapters. The consumers of those messages are *applications* which connect to the AMQP Messaging Network using Hono's north bound Telemetry API.

The connection you are setting up is to the north bound Telemetry API endpoint of the example deployment (port 15672 of the dispatch router). So the message handler you register on the connection represents an *application* consuming telemetry data. That is all fine and correct.

However, you cannot publish a message using the north bound Telemetry API. Instead, you should publish telemetry data via one of Hono's protocol adapters, e.g. the HTTP adapter as shown in the Getting Started guide.
