### ISSUE TITLE
HonoConnection: Make sender/receiver creation wait on reconnect attempt

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1673]
Currently, when a `HonoConnection` gets disconnected and subsequently tries to reconnect itself, all sender/receiver link creation attempts fail immediately while the reconnect is still in progress.
This is done in the `checkConnected` method, invoked when a link gets created.

<details>
<summary>See stack trace of a "not connected" error there.</summary>

~~~
07:05:57.803 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.CachingClientFactory - failed to create new client for [registration/mytenant]
org.eclipse.hono.client.ServerErrorException: not connected
  at org.eclipse.hono.client.impl.HonoConnectionImpl.checkConnected(HonoConnectionImpl.java:256)
  at org.eclipse.hono.client.impl.HonoConnectionImpl.checkConnected(HonoConnectionImpl.java:248)
  at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$createReceiver$21(HonoConnectionImpl.java:737)
  at org.eclipse.hono.util.HonoProtonHelper.executeOrRunOnContext(HonoProtonHelper.java:180)
  at org.eclipse.hono.client.impl.HonoConnectionImpl.executeOrRunOnContext(HonoConnectionImpl.java:229)
  at org.eclipse.hono.client.impl.HonoConnectionImpl.createReceiver(HonoConnectionImpl.java:736)
  at org.eclipse.hono.client.impl.HonoConnectionImpl.createReceiver(HonoConnectionImpl.java:717)
  at org.eclipse.hono.client.impl.HonoConnectionImpl.createReceiver(HonoConnectionImpl.java:707)
  at org.eclipse.hono.client.impl.AbstractRequestResponseClient.createReceiver(AbstractRequestResponseClient.java:409)
  at org.eclipse.hono.client.impl.AbstractRequestResponseClient.createLinks(AbstractRequestResponseClient.java:391)
  at org.eclipse.hono.client.impl.RegistrationClientImpl.create(RegistrationClientImpl.java:151)
  at org.eclipse.hono.client.impl.RegistrationClientFactoryImpl.lambda$getOrCreateRegistrationClient$1(RegistrationClientFactoryImpl.java:74)
  at org.eclipse.hono.client.impl.CachingClientFactory.getOrCreateClient(CachingClientFactory.java:174)
  at org.eclipse.hono.client.impl.CachingClientFactory.getOrCreateClient(CachingClientFactory.java:146)
  at org.eclipse.hono.client.impl.RegistrationClientFactoryImpl.lambda$getOrCreateRegistrationClient$2(RegistrationClientFactoryImpl.java:72)
  at org.eclipse.hono.util.HonoProtonHelper.executeOrRunOnContext(HonoProtonHelper.java:180)
  at org.eclipse.hono.client.impl.HonoConnectionImpl.executeOrRunOnContext(HonoConnectionImpl.java:229)
  at org.eclipse.hono.client.impl.RegistrationClientFactoryImpl.getOrCreateRegistrationClient(RegistrationClientFactoryImpl.java:71)
  at org.eclipse.hono.service.AbstractProtocolAdapterBase.getRegistrationClient(AbstractProtocolAdapterBase.java:914)
  at org.eclipse.hono.service.AbstractProtocolAdapterBase.lambda$getRegistrationAssertion$28(AbstractProtocolAdapterBase.java:950)
  at io.vertx.core.Future.lambda$compose$1(Future.java:265)
  at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
  at io.vertx.core.Future.compose(Future.java:261)
  at org.eclipse.hono.service.AbstractProtocolAdapterBase.getRegistrationAssertion(AbstractProtocolAdapterBase.java:950)
  at org.eclipse.hono.adapter.http.AbstractVertxBasedHttpProtocolAdapter.doUploadMessage(AbstractVertxBasedHttpProtocolAdapter.java:637)
  at org.eclipse.hono.adapter.http.AbstractVertxBasedHttpProtocolAdapter.uploadTelemetryMessage(AbstractVertxBasedHttpProtocolAdapter.java:541)
  at org.eclipse.hono.adapter.http.AbstractVertxBasedHttpProtocolAdapter.uploadTelemetryMessage(AbstractVertxBasedHttpProtocolAdapter.java:515)
  at org.eclipse.hono.adapter.http.impl.VertxBasedHttpProtocolAdapter.handlePostTelemetry(VertxBasedHttpProtocolAdapter.java:306)
~~~

</details>

To prevent these failures (possibly leading to event/telemetry messages not getting delivered), we could let all `checkConnected` invocations wait on the current reconnect attempt (timing it out after the connect-timeout period).

**Comment by calohmn** [comment]
See followup  #1691 for adding a timeout mechanism.
