### ISSUE TITLE
Rare sender/receiver creation error

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1718]
We have seen the following error in a protocol adapter log while the AMQP messaging network component got restarted:
````
15:26:17.575 [vert.x-eventloop-thread-0] INFO  o.e.h.client.impl.HonoConnectionImpl - link establishment [peer: xx] timed out after 1000ms
15:26:17.576 [vert.x-eventloop-thread-0] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: null
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:54)
	at org.apache.qpid.proton.engine.impl.LinkImpl.postFinal(LinkImpl.java:128)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:52)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.free(EndpointImpl.java:191)
	at io.vertx.proton.impl.ProtonLinkImpl.free(ProtonLinkImpl.java:303)
	at io.vertx.proton.impl.ProtonReceiverImpl.free(ProtonReceiverImpl.java:41)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.onTimeOut(HonoConnectionImpl.java:810)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$createReceiver$19(HonoConnectionImpl.java:795)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:911)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:875)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:901)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
````
This caused the receiver creation future to not get finished.

<details>
<summary>Here is another variant of this stacktrace.</summary>

~~~
java.lang.IllegalStateException: null
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:54)
	at org.apache.qpid.proton.engine.impl.SessionImpl.postFinal(SessionImpl.java:138)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:52)
	at org.apache.qpid.proton.engine.impl.LinkImpl.postFinal(LinkImpl.java:128)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:52)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.free(EndpointImpl.java:191)
	at io.vertx.proton.impl.ProtonLinkImpl.free(ProtonLinkImpl.java:303)
	at io.vertx.proton.impl.ProtonReceiverImpl.free(ProtonReceiverImpl.java:41)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.onTimeOut(HonoConnectionImpl.java:810)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$createReceiver$19(HonoConnectionImpl.java:795)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:911)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:875)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:901)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
~~~

</details>

<details>
<summary>And here another during *sender* creation.</summary>

~~~
java.lang.IllegalStateException: null
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:54)
	at org.apache.qpid.proton.engine.impl.LinkImpl.postFinal(LinkImpl.java:128)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.decref(EndpointImpl.java:52)
	at org.apache.qpid.proton.engine.impl.EndpointImpl.free(EndpointImpl.java:191)
	at io.vertx.proton.impl.ProtonLinkImpl.free(ProtonLinkImpl.java:303)
	at io.vertx.proton.impl.ProtonSenderImpl.free(ProtonSenderImpl.java:33)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.onTimeOut(HonoConnectionImpl.java:810)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$createSender$12(HonoConnectionImpl.java:698)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:911)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:875)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:901)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

~~~

</details>

The errors above lead to the assumption that somehow one of the Proton Link/Session/Connection/Transport objects got corrupted.
An explanation could be that there was an exception in one of the handlers associated with these objects (e.g. closeHandler, detachHandler, etc.).
Such exceptions don't get logged and cause a corrupted state of the Proton object (see https://github.com/vert-x3/vertx-proton/issues/94).
Therefore a solution could be to add exception handling for these handlers.

Another issue is that the `link establishment timed out` log message is misleading - the failure to establish the link is caused by the closed connection, not by the "attach" frame not getting received on an intact connection.

EDIT: the origin actually wasn't an unhandled exception thrown in one of the handlers - see [comment below](https://github.com/eclipse/hono/issues/1718#issuecomment-580672008).

**Comment by calohmn** [comment]
While there were several restarts of the AMQP messaging network component, the log showed these connection related entries:
````
January 20th 2020, 15:57:47.294 starting attempt [#13] to connect to server [xx]
January 20th 2020, 15:57:45.723 starting attempt [#12] to connect to server [xx]
January 20th 2020, 15:57:43.023 starting attempt [#11] to connect to server [xx]
January 20th 2020, 15:57:39.328 starting attempt [#10] to connect to server [xx]
January 20th 2020, 15:57:36.821 starting attempt [#9] to connect to server [xx]
January 20th 2020, 15:57:31.229 starting attempt [#8] to connect to server [xx]
January 20th 2020, 15:57:30.567 starting attempt [#7] to connect to server [xx]
January 20th 2020, 15:57:23.985 starting attempt [#6] to connect to server [xx]
January 20th 2020, 15:57:18.619 starting attempt [#5] to connect to server [xx]
January 20th 2020, 15:57:13.340 starting attempt [#4] to connect to server [xx]
January 20th 2020, 15:57:13.240 starting attempt [#3] to connect to server [xx]
January 20th 2020, 15:57:08.219 starting attempt [#2] to connect to server [xx]
  January 20th 2020, 15:57:08.219 lost connection to server [xx]
January 20th 2020, 15:35:12.395 starting attempt [#27] to connect to server [xx]
January 20th 2020, 15:35:06.850 starting attempt [#26] to connect to server [xx]
January 20th 2020, 15:35:00.702 starting attempt [#25] to connect to server [xx]
January 20th 2020, 15:34:55.332 starting attempt [#24] to connect to server [xx]
January 20th 2020, 15:34:49.350 starting attempt [#23] to connect to server [xx]
January 20th 2020, 15:34:45.643 starting attempt [#22] to connect to server [xx]
January 20th 2020, 15:34:39.367 starting attempt [#21] to connect to server [xx]
January 20th 2020, 15:34:33.231 starting attempt [#20] to connect to server [xx]
January 20th 2020, 15:34:32.547 starting attempt [#19] to connect to server [xx]
January 20th 2020, 15:34:31.775 starting attempt [#18] to connect to server [xx]
January 20th 2020, 15:34:27.005 starting attempt [#17] to connect to server [xx]
January 20th 2020, 15:34:20.176 starting attempt [#16] to connect to server [xx]
January 20th 2020, 15:34:17.877 starting attempt [#15] to connect to server [xx]
January 20th 2020, 15:23:59.552 starting attempt [#3] to connect to server [xx]
January 20th 2020, 15:23:54.475 starting attempt [#2] to connect to server [xx]
  January 20th 2020, 15:23:54.474 lost connection to server [xx]
January 20th 2020, 15:14:37.409 starting attempt [#2] to connect to server [xx]
  January 20th 2020, 15:14:37.409 lost connection to server [xx]
January 20th 2020, 15:06:58.337 attempt [#35]: connected to server [xx]; remote container: qdrouterd-1
January 20th 2020, 15:06:58.337 connection to container [qdrouterd-1] at [amqps://xx] open
January 20th 2020, 15:06:58.209 starting attempt [#35] to connect to server [xx]
January 20th 2020, 15:06:53.224 starting attempt [#34] to connect to server [xx]
January 20th 2020, 15:06:50.255 starting attempt [#33] to connect to server [xx]
January 20th 2020, 15:06:50.143 starting attempt [#32] to connect to server [xx]
January 20th 2020, 15:06:48.123 starting attempt [#31] to connect to server [xx]
January 20th 2020, 14:40:23.026 starting attempt [#1751] to connect to server [xx]
January 20th 2020, 14:38:44.023 starting attempt [#34] to connect to server [xx]
January 20th 2020, 14:38:43.533 starting attempt [#33] to connect to server [xx]
January 20th 2020, 14:38:42.877 starting attempt [#32] to connect to server [xx]
January 20th 2020, 14:38:36.913 starting attempt [#31] to connect to server [xx]
January 20th 2020, 14:38:32.836 starting attempt [#30] to connect to server [xx]
January 20th 2020, 14:38:27.178 starting attempt [#29] to connect to server [xx]
January 20th 2020, 14:38:21.022 starting attempt [#28] to connect to server [xx]
January 20th 2020, 14:38:15.805 starting attempt [#27] to connect to server [xx]
January 20th 2020, 14:38:14.241 starting attempt [#26] to connect to server [xx]
January 20th 2020, 14:38:09.894 starting attempt [#25] to connect to server [xx]
January 20th 2020, 14:38:06.143 starting attempt [#24] to connect to server [xx]
January 20th 2020, 14:38:01.864 starting attempt [#23] to connect to server [xx]
January 20th 2020, 14:37:56.669 starting attempt [#22] to connect to server [xx]
January 20th 2020, 14:37:53.210 starting attempt [#21] to connect to server [xx]
````

The fact that there is no `starting attempt [#14]` entry in the above timeframe leads to the assumption that the connection attempt 14 was actually performed some hours earlier and then a disconnect occured where possibly an exception during disconnect handler processing lead to the connection attempt counter not being reset.
So this could be a further indication that there exception handling in the handlers is here needed - at least to find the bug that is causing this.

**Comment by calohmn** [comment]
We were able to reproduce the above exception in a load-test environment, creating many links, and also in a small test class.
The issue occurs when Hono throws a "link establishment timed out" exception and subsequently closes the link and also calls "link.free()" to free up ressources, *and* when the server still responds with an "attach" frame afterwards, before finally sending a "detach".

There is now this Proton-J issue for that: https://issues.apache.org/jira/browse/PROTON-2177

Solution/workaround would to omit calling "link.free()" on linkEstablishmentTimeout handling, hoping that the server will finally respond with a "detach" frame after which we then can call "link.free()".

I'll update the PR accordingly.
