### ISSUE TITLE
Unhandled exception in link establishment timeout handling

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#1720]
Log excerpt:
````
January 22nd 2020, 10:13:52.519 INFO org.eclipse.hono.client.impl.HonoConnectionImpl link establishment [peer: XXX] timed out after 1000ms
January 22nd 2020, 10:13:52.519 ERROR io.vertx.core.impl.ContextImpl Unhandled exception
java.lang.IllegalStateException: Result is already complete: failed
  at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:101)
  at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:153)
  at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
  at org.eclipse.hono.client.impl.CachingClientFactory.lambda$getOrCreateClient$2(CachingClientFactory.java:185)
  at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:170)
  at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:100)
  at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:153)
  at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
  at io.vertx.core.impl.FailedFuture.setHandler(FailedFuture.java:48)
  at io.vertx.core.Future.lambda$recover$4(Future.java:394)
  at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:170)
  at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:100)
  at io.vertx.core.Future.lambda$map$2(Future.java:308)
  at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:170)
  at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:100)
  at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:153)
  at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
  at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:170)
  at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:100)
  at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:153)
  at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
  at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:170)
  at org.eclipse.hono.client.impl.HonoConnectionImpl.onTimeOut(HonoConnectionImpl.java:811)
  at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$createReceiver$19(HonoConnectionImpl.java:795)
[...]
````
<details>
<summary>(Error with which the Future was about to be completed.)</summary>

~~~
January 22nd 2020, 10:13:52.519 DEBUG org.eclipse.hono.client.impl.CachingClientFactory   failed to create new client for [testTenant/testDevice]
org.eclipse.hono.client.ServerErrorException: Error Code: 503
  at org.eclipse.hono.client.impl.HonoConnectionImpl.onTimeOut(HonoConnectionImpl.java:811)
  at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$createReceiver$19(HonoConnectionImpl.java:795)
  at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:911)
  at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:875)
  at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
  at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
  at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
  at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180)
  at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:901)
[...]
~~~

</details>

The above ERROR log entry does not cause any problems but can cause confusion when analyzing log files.

**Comment by calohmn** [comment]
I guess in the above scenario there was a disconnect before the link establishment timeout.
The connectionFailure handling in `CachingClientFactory` here
https://github.com/eclipse/hono/blob/d3ee2915f902d8c5b6267f991d11e5038849e3be/client/src/main/java/org/eclipse/hono/client/impl/CachingClientFactory.java#L161-L168
probably had completed the Future already, causing the following link creation handler (with the link establishment timeout result) to encounter an already completed Future.

First guess would be that the `CachingClientFactory` connectionFailure handling can be removed, now that the `HonoConnectionImpl` link creation implementation also takes concurrent disconnects into account (see PR #1719).

**Comment by sophokles73** [comment]
@calohmn is this still an issue?

**Comment by calohmn** [comment]
Yes, I think it can still happen. I'll provide a fix.
