### ISSUE TITLE
create device and psk credentials

### ISSUE THREAD

**Issue by boaks** [eclipse/hono#1725]
I tried to follow [Device Registry Management API Specification](https://www.eclipse.org/hono/docs/api/management/) but end up in error messages:

```
15:13:09.173 [vert.x-eventloop-thread-0] DEBUG o.e.h.s.m.d.DeviceManagementHttpEndpoint - creating device [tenant: DEFAULT_TENANT, device: D580061, payload: {"enabled":true}]
15:13:09.173 [vert.x-eventloop-thread-0] DEBUG o.e.h.d.AutowiredDeviceManagementAdapter - registering device [D580061] for tenant [DEFAULT_TENANT]
15:13:09.173 [vert.x-eventloop-thread-0] DEBUG o.e.h.d.AutowiredDeviceManagementAdapter - sending response as direct reply to request [operation: create]
15:13:09.180 [vert.x-eventloop-thread-0] DEBUG o.e.h.s.http.DefaultFailureHandler - handling failed route for request [method: PUT, URI: http://10.152.183.145:28080/v1/credentials/DEFAULT_TENANT/D580061, status: -1] - {"auth-id":"A480061", "type" : "psk", "enabled": true, "secrets" : [{"key" : "Y29hcC1zZWNyZXQ=" }]}
org.eclipse.hono.client.ClientErrorException: Invalid JSON
                at org.eclipse.hono.service.http.AbstractHttpEndpoint.extractRequiredJson(AbstractHttpEndpoint.java:139)
                at org.eclipse.hono.service.http.AbstractHttpEndpoint.extractRequiredJsonArrayPayload(AbstractHttpEndpoint.java:185)
                at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
```

According the scheme in the above docu link, I miss to see the error ;-(.

**Comment by kaniyan** [comment]
It accepts a credentials set. So the json body should be 

```
[
    {
        "auth-id": "A480061",
        "type": "psk",
        "enabled": true,
        "secrets": [
            {
                "key": "Y29hcC1zZWNyZXQ="
            }
        ]
    }
]
```

**Comment by sophokles73** [comment]
It would be helpful if you could post the command that you have used to register the device.

**Comment by boaks** [comment]
I was focused on the json, and that was already contained in the logs.
