### ISSUE TITLE
ConcurrentModificationException in handleTenantTimeout

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2031]
We saw the following exception in a protocol adapter log:
````
ERROR io.vertx.core.impl.ContextImpl Unhandled exception
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.eclipse.hono.client.impl.ProtocolAdapterCommandConsumerFactoryImpl.handleTenantTimeout(ProtocolAdapterCommandConsumerFactoryImpl.java:311)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:271)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:249)
	at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:573)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$5(EventBusImpl.java:532)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
[...]
````

**Comment by sophokles73** [comment]
@calohmn which version are we talking about?

**Comment by calohmn** [comment]
@sophokles73 This occurred with Hono 1.2.3.

**Comment by calohmn** [comment]
Fixed via https://github.com/eclipse/hono/commit/6c5b1371a10ecaa68f5cbc2e71f388f82a0ac643 (master) and https://github.com/eclipse/hono/commit/57537934d6e9402ef56e15dd89177e7bd6bef53f, https://github.com/eclipse/hono/commit/187757ed93a183246bac0931e43f5c31e5b36560 (1.2.x).
