### ISSUE TITLE
No re-connection attempt from Hono to QPid after "Disconnected" exception

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#207]
We got into a scenario, where the connection from Hono to the Dispatch Router got lost and a re-connection attempt was made. This connection attempt didn't succeed - a "Disconnected" exception was thrown. 
From then on, no re-connection attempts were made, leaving Hono in an unusable state.

Hono log output:
```
15:51:07.162 [vert.x-eventloop-thread-1] INFO o.e.h.c.ConnectionFactoryImpl - connecting to AMQP 1.0 container [amqps://qdrouter:5673]
15:51:07.548 [vert.x-eventloop-thread-1] INFO o.e.h.c.ConnectionFactoryImpl - connected to AMQP 1.0 container [amqps://qdrouter:5673], opening connection ...
15:51:07.552 [vert.x-eventloop-thread-1] INFO o.e.h.c.ConnectionFactoryImpl - connection to container [Hono.Example.Router] at [amqps://qdrouter:5673] open
15:51:11.564 [vert.x-eventloop-thread-1] WARN o.e.h.e.i.ForwardingEventDownstreamAdapter - lost connection to downstream container [Hono.Example.Router], closing upstream receivers ...
15:51:11.771 [vert.x-eventloop-thread-1] INFO o.e.h.e.i.ForwardingEventDownstreamAdapter - attempting to re-connect to downstream container
15:51:11.772 [vert.x-eventloop-thread-1] INFO o.e.h.config.ClientConfigProperties - using certificates from file [/run/secrets/trusted-certs.pem] as trust anchor
15:51:11.772 [vert.x-eventloop-thread-1] INFO o.e.h.config.ClientConfigProperties - using key & certificate from PKCS12 key store [/run/secrets/honoKeyStore.p12] for identity
15:51:11.772 [vert.x-eventloop-thread-1] INFO o.e.h.c.ConnectionFactoryImpl - connecting to AMQP 1.0 container [amqps://qdrouter:5673]
15:51:12.149 [vert.x-eventloop-thread-1] WARN o.e.h.c.ConnectionFactoryImpl - can't connect to AMQP 1.0 container [amqps://qdrouter:5673]
io.vertx.core.VertxException: Disconnected
	at io.vertx.proton.impl.ProtonClientImpl.lambda$null$0(ProtonClientImpl.java:74) ~[vertx-proton-3.4.1.jar!/:na]
	at io.vertx.proton.impl.ProtonConnectionImpl.fireDisconnect(ProtonConnectionImpl.java:370) ~[vertx-proton-3.4.1.jar!/:na]
	at io.vertx.proton.impl.ProtonTransport.handleSocketEnd(ProtonTransport.java:88) ~[vertx-proton-3.4.1.jar!/:na]
	at io.vertx.core.net.impl.NetSocketImpl.handleClosed(NetSocketImpl.java:297) ~[vertx-core-3.4.1.jar!/:na]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335) ~[vertx-core-3.4.1.jar!/:na]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193) ~[vertx-core-3.4.1.jar!/:na]
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:97) ~[vertx-core-3.4.1.jar!/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.handler.stream.ChunkedWriteHandler.channelInactive(ChunkedWriteHandler.java:146) ~[netty-handler-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360) ~[netty-codec-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325) ~[netty-codec-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:861) ~[netty-handler-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
```
```
15:51:12.161 [vert.x-eventloop-thread-1] INFO o.e.h.e.i.ForwardingEventDownstreamAdapter - failed to connect to downstream container
io.vertx.core.VertxException: Disconnected
	at io.vertx.proton.impl.ProtonClientImpl.lambda$null$0(ProtonClientImpl.java:74) ~[vertx-proton-3.4.1.jar!/:na]
	at io.vertx.proton.impl.ProtonConnectionImpl.fireDisconnect(ProtonConnectionImpl.java:370) ~[vertx-proton-3.4.1.jar!/:na]
	at io.vertx.proton.impl.ProtonTransport.handleSocketEnd(ProtonTransport.java:88) ~[vertx-proton-3.4.1.jar!/:na]
	at io.vertx.core.net.impl.NetSocketImpl.handleClosed(NetSocketImpl.java:297) ~[vertx-core-3.4.1.jar!/:na]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335) ~[vertx-core-3.4.1.jar!/:na]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193) ~[vertx-core-3.4.1.jar!/:na]
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:97) ~[vertx-core-3.4.1.jar!/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.handler.stream.ChunkedWriteHandler.channelInactive(ChunkedWriteHandler.java:146) ~[netty-handler-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360) ~[netty-codec-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325) ~[netty-codec-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:861) ~[netty-handler-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445) ~[netty-transport-4.1.8.Final.jar!/:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.8.Final.jar!/:4.1.8.Final]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
15:51:34.756 [vert.x-eventloop-thread-1] INFO org.eclipse.hono.server.HonoServer - opening new session with client [Hono MQTT Adapter-6373c30e-e32b-4f8e-98f6-bfb749f75d13]
15:51:34.767 [vert.x-eventloop-thread-1] DEBUG org.eclipse.hono.server.HonoServer - client [Hono MQTT Adapter-6373c30e-e32b-4f8e-98f6-bfb749f75d13] wants to open a link for sending messages [address: Target{address='telemetry/DEFAULT_TENANT', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}]
15:51:34.769 [vert.x-eventloop-thread-0] DEBUG o.e.h.a.i.InMemoryAuthorizationService - checking [subject: mqtt-adapter, resource: ResourceEntry[resource: telemetry/*, operation: null], permission: WRITE]
15:51:34.770 [vert.x-eventloop-thread-0] DEBUG o.e.h.a.i.InMemoryAuthorizationService - checking [subject: mqtt-adapter, resource: ResourceEntry[resource: telemetry/DEFAULT_TENANT, operation: null], permission: WRITE]
15:51:34.774 [vert.x-eventloop-thread-0] DEBUG o.e.h.s.a.BaseAuthorizationService - subject [mqtt-adapter] is allowed to WRITE on resource [telemetry/DEFAULT_TENANT]
15:51:34.778 [vert.x-eventloop-thread-1] WARN o.e.h.t.i.ForwardingTelemetryDownstreamAdapter - can't create downstream sender [con: aabb1c4c-8882-4e73-abf4-d187caf014ff, link: 63e8e349-8f80-4cff-9489-64e3f7852379]
io.vertx.core.impl.NoStackTraceThrowable: downstream connection must be opened before creating sender
```
The dispatch router log didn't contain relevant output.

**Comment by sophokles73** [comment]
Hmm, I hope that this problem is also addressed by the fix for #209.

**Comment by sophokles73** [comment]
@calohmn is this fixed for you?

**Comment by calohmn** [comment]
It seems to be fixed, I haven't seen the error again.
