### ISSUE TITLE
Error starting device-connection service component

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2072]
Hono 1.3.0-M3:
The device connection service component can't connect to the Infinispan data grad.
There is this exception in the log:
````
[HotRod-client-async-pool-1-1] ERROR org.infinispan.HOTROD - ISPN004007: Exception encountered. Retry 10 out of 10
org.infinispan.client.hotrod.exceptions.TransportException: javax.security.sasl.SaslException: ELY05051: Callback handler does not support credential acquisition [Caused by java.security.NoSuchAlgorithmException: class configured for PasswordFactory (provider: WildFlyElytron) cannot be found.]
	at org.infinispan.client.hotrod.impl.transport.netty.ActivationHandler.exceptionCaught(ActivationHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
	at org.infinispan.client.hotrod.impl.transport.netty.AuthHandler.lambda$channelActive$2(AuthHandler.java:87)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at org.infinispan.client.hotrod.impl.operations.HotRodOperation.complete(HotRodOperation.java:165)
	at org.infinispan.client.hotrod.impl.operations.AuthOperation.acceptResponse(AuthOperation.java:64)
	at org.infinispan.client.hotrod.impl.transport.netty.HeaderDecoder.decode(HeaderDecoder.java:145)
	at org.infinispan.client.hotrod.impl.transport.netty.HintedReplayingDecoder.callDecode(HintedReplayingDecoder.java:94)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javax.security.sasl.SaslException: ELY05051: Callback handler does not support credential acquisition
	at org.wildfly.security.mechanism._private.MechanismUtil.getPasswordCredential(MechanismUtil.java:139)
	at org.wildfly.security.mechanism.scram.ScramClient.handleInitialChallenge(ScramClient.java:245)
	at org.wildfly.security.sasl.scram.ScramSaslClient.evaluateMessage(ScramSaslClient.java:75)
	at org.wildfly.security.sasl.util.AbstractSaslParticipant.evaluateMessage(AbstractSaslParticipant.java:219)
	at org.wildfly.security.sasl.util.AbstractSaslClient.evaluateChallenge(AbstractSaslClient.java:98)
	at org.infinispan.client.hotrod.impl.transport.netty.AuthHandler.evaluateChallenge(AuthHandler.java:106)
	at org.infinispan.client.hotrod.impl.transport.netty.AuthHandler.access$200(AuthHandler.java:26)
	at org.infinispan.client.hotrod.impl.transport.netty.AuthHandler$ChallengeEvaluator.apply(AuthHandler.java:124)
	at org.infinispan.client.hotrod.impl.transport.netty.AuthHandler$ChallengeEvaluator.apply(AuthHandler.java:110)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	... 26 common frames omitted
Caused by: java.security.NoSuchAlgorithmException: class configured for PasswordFactory (provider: WildFlyElytron) cannot be found.
	at java.base/java.security.Provider$Service.getImplClass(Unknown Source)
	at java.base/java.security.Provider$Service.newInstance(Unknown Source)
	at org.wildfly.security.password.PasswordFactory.getInstance(PasswordFactory.java:119)
	at org.wildfly.security.mechanism._private.MechanismUtil.getPasswordCredential(MechanismUtil.java:78)
	... 35 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.wildfly.security.password.impl.PasswordFactorySpiImpl
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 common frames omitted
````

**Comment by sophokles73** [comment]
I assume you have tried to deploy using the Hono Helm chart? Can you post your command line?

**Comment by calohmn** [comment]
````
# in directory iot-packages/charts
helm install --dependency-update -n hono --set prometheus.createInstance=false --set grafana.enabled=false --set deviceConnectionService.enabled=true --set dataGridExample.enabled=true eclipse-hono hono/
```` 
Having adapted the `values.yaml` to the `1.3.0-M3` images (I've built them locally).

**Comment by sophokles73** [comment]
@calohmn I am able to reproduce the issue and have also found the reason why the connection fails. However, this is an issue with the Helm chart, not Hono itself. Thus I would like to kindly ask you to open an issue towards the Hono chart in the IoT Packages project and close this issue.
I will then create a PR fixing the issue.

**Comment by calohmn** [comment]
Yes, IoT Packages issue is https://github.com/eclipse/packages/issues/115.
