### ISSUE TITLE
IllegalStateException in AbstractRequestResponseClient

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2074]
During some recent failed integration test runs in Travis, there were such kind of exceptions in the log:
````
13:23:04.633 [vert.x-eventloop-thread-2] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: Result is already complete: failed
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:112)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:176)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21)
	at org.eclipse.hono.client.impl.AbstractRequestResponseClient.lambda$sendRequest$4(AbstractRequestResponseClient.java:881)
	at io.vertx.proton.impl.ProtonDeliveryImpl.fireUpdate(ProtonDeliveryImpl.java:158)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:161)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:379)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:101)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:357)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
[...]
13:23:07.134 [vert.x-eventloop-thread-2] ERROR o.e.h.t.amqp.CommandAndControlAmqpIT - failed to establish connection to AMQP adapter [host: localhost, port: 32785]
org.eclipse.hono.client.ServerErrorException: connection to server lost
	at org.eclipse.hono.client.impl.ClientFactory.lambda$createClient$0(ClientFactory.java:91)
	at org.eclipse.hono.client.impl.ClientFactory.failAllCreationRequests(ClientFactory.java:69)
	at org.eclipse.hono.client.impl.ClientFactory.clearState(ClientFactory.java:62)
	at org.eclipse.hono.client.impl.ClientFactory.clearState(ClientFactory.java:50)
	at org.eclipse.hono.client.impl.ApplicationClientFactoryImpl.onDisconnect(ApplicationClientFactoryImpl.java:224)
	at org.eclipse.hono.client.impl.AbstractHonoClientFactory.lambda$new$0(AbstractHonoClientFactory.java:52)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.notifyDisconnectHandler(HonoConnectionImpl.java:533)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.notifyDisconnectHandlers(HonoConnectionImpl.java:523)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.clearState(HonoConnectionImpl.java:516)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$closeConnection$29(HonoConnectionImpl.java:1111)
	at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$closeConnection$30(HonoConnectionImpl.java:1117)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:923)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:887)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:221)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:913)
````
That means that closing the connection while a request/response is being handled via the `AbstractRequestResponseClient` seems to produce such an unhandled exception.

(These errors occurred mostly in the `CommandAndControlAmqpIT` tests but also in `CommandAndControlMqttIT`. The reason why the connection from the test client to the adapter got closed during the test run is still unclear.)

**Comment by sophokles73** [comment]
I am not sure if these two log entries are related. The first one seems to have occurred in the context of sending a one-way command as code location
> org.eclipse.hono.client.impl.AbstractRequestResponseClient.lambda$sendRequest$4(AbstractRequestResponseClient.java:881)

suggests. If I am not mistaken then the only reason why the resultHandler could have been failed before is due to the request having timed out *before* the disposition update has been received from the adapter. WDYT?

**Comment by calohmn** [comment]
@sophokles73 Right, it looks like a timeout has happened and it's good you increased some timeouts here already. I've been seeing errors in some more test methods, so I'm currently looking into adapting timeouts there as well.
