### ISSUE TITLE
NPE in AMQP adpter if no content-type set

### ISSUE THREAD

**Issue by b-abel** [eclipse/hono#2338]
The AMQP adapter throws a nullpointer exception when a telemetry message without a content-type is received.
This results in a log like the following: 

    18:16:53.031 [vert.x-eventloop-thread-3] WARN  o.eclipse.hono.tracing.TracingHelper - An unexpected error occurred!
    java.lang.NullPointerException: null
    at java.base/java.util.Objects.requireNonNull(Unknown Source)
    at org.eclipse.hono.adapter.client.telemetry.amqp.ProtonBasedDownstreamSender.sendTelemetry(ProtonBasedDownstreamSender.java:121)
    at org.eclipse.hono.adapter.amqp.impl.VertxBasedAmqpProtocolAdapter.lambda$doUploadMessage$64(VertxBasedAmqpProtocolAdapter.java:1122)
    at io.vertx.core.Future.lambda$compose$3(Future.java:368)

**Comment by sophokles73** [comment]
@b-abel does this also affect 1.4.x or 1.3.x?

**Comment by b-abel** [comment]
@sophokles73, no. The NPE appears with the new client interfaces. The downstream senders now throw the exception if the content-type is not set.

**Comment by b-abel** [comment]
In 1.4 (i.e. before the new client interfaces) the missing content-type is added in the `MessageHelper.addProperties()` method.
