### ISSUE TITLE
Connect Hono service inside OpenShift - CodeReady Container

### ISSUE THREAD

**Issue by truong11t2** [eclipse/hono#2371]
Hi,

I deployed Hono inside CodeReady Containers and it's running as fine as below. 

![image](https://user-images.githubusercontent.com/59316294/102275088-32969000-3f25-11eb-8eec-68c43d0b804e.png)

I tried to reach service via external IP. However due to the issue [https://github.com/code-ready/crc/issues/1491](url) which I believed I will not able to connect service via external IP. Hence, I exposed routes for those services on OpenShift web interface.

![image](https://user-images.githubusercontent.com/59316294/102273774-24477480-3f23-11eb-942f-f67df403e322.png)
Then I can execute below cmd for device registry which is http protocol.

`curl -i -X POST http://device-registry-hono.apps-crc.testing/v1/tenants
HTTP/1.1 201 Created
etag: e9cd865e-0b20-43f2-af52-c15cfe45cf79
location: /v1/tenants/63e5d661-c9e7-4d4e-81b1-66ce31110697
content-type: application/json; charset=utf-8
content-length: 45
Set-Cookie: d30cfb1a2c870c5b88445b197a83332c=569508a9358ad00836c0af4e49959799; path=/; HttpOnly

{"id":"63e5d661-c9e7-4d4e-81b1-66ce31110697"}`

However, when I execute hono-client I get error which I think the route that I link to services will not working with non-http protocol. So do you know how to overcome this in case I want to use hono services via url only?

`java -jar hono-cli.jar --hono.client.host=http://dispatch-router-hono.apps-crc.testing --hono.client.port=80 --hono.client.username=consumer@HONO --hono.client.password=verysecret --spring.profiles.active=receiver --tenant.id=$MY_TENANT

  ______     _ _                  _    _                   
 |  ____|   | (_)                | |  | |                  
 | |__   ___| |_ _ __  ___  ___  | |__| | ___  _ __   ___  
 |  __| / __| | | '_ \/ __|/ _ \ |  __  |/ _ \| '_ \ / _ \ 
 | |___| (__| | | |_) \__ \  __/ | |  | | (_) | | | | (_) |
 |______\___|_|_| .__/|___/\___| |_|  |_|\___/|_| |_|\___/ 
                | |                                        
                |_|                                        

Eclipse Hono Example Client  (v1.4.0)
using Spring Boot  (v2.2.7.RELEASE)

Go to https://www.eclipse.org/hono for more information.

20:48:26.522 [main] INFO  org.eclipse.hono.cli.Application - Starting Application v1.4.0 on localhost.localdomain with PID 5960 (/home/truong/Downloads/hono-cli.jar started by truong in /home/truong/Downloads)
20:48:26.525 [main] INFO  org.eclipse.hono.cli.Application - The following profiles are active: receiver
20:48:27.436 [main] INFO  org.eclipse.hono.cli.Application - running command line client in role(s): receiver
20:48:28.154 [main] INFO  org.eclipse.hono.cli.Application - Started Application in 2.776 seconds (JVM running for 3.823)
20:48:31.986 [vert.x-eventloop-thread-0] INFO  o.e.h.client.impl.HonoConnectionImpl - max number of attempts [5] to re-connect to server [http://dispatch-router-hono.apps-crc.testing:80, role: unknown] have been made, giving up
20:48:31.997 [vert.x-eventloop-thread-0] INFO  o.e.h.client.impl.HonoConnectionImpl - stopping connection attempt to server [http://dispatch-router-hono.apps-crc.testing:80, role: unknown] due to terminal error
java.net.UnknownHostException: failed to resolve 'http://dispatch-router-hono.apps-crc.testing' after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:927)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:886)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:358)
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:545)
	at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:64)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:402)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:201)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:193)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
20:48:32.001 [vert.x-eventloop-thread-0] ERROR org.eclipse.hono.cli.app.Receiver - Error occurred during initialization of receiver: failed to connect`

**Comment by truong11t2** [comment]
One more thing, if I use browser, I get 502 error code
![image](https://user-images.githubusercontent.com/59316294/102277257-4abbde80-3f28-11eb-8e7c-1a1ee5087467.png)

**Comment by sophokles73** [comment]
@ctron can you help out with this one?

**Comment by truong11t2** [comment]
Hi @sophokles73 
Thank you for your response. I actually made it work. Instead using route, I used the IP address of CRC (VM machine which running openshift) and some how it allowed me to reach the services.

`curl -i -u a3425b18-cd03-447b-8a3c-6f9a315411dd@f6801d88-4fcf-49ed-90e6-51522070d18a:my-pwd -H 'Content-Type: application/json' --data-binary '{"temp": 5}' 192.168.130.11:30080/telemetry`

`HTTP/1.1 202 Accepted
content-length: 0`

I want now to perform a secure connection to services by using secure port in this case `30443`. But I get no reply from server.

`curl -i -u a3425b18-cd03-447b-8a3c-6f9a315411dd@f6801d88-4fcf-49ed-90e6-51522070d18a:my-pwd -H 'Content-Type: application/json' --data-binary '{"temp": 5}' 192.168.130.11:30443/telemetry`

`curl: (52) Empty reply from server`

I think I should do some configuration. However, when I look into the guideline at `Admin Guide` I can only see the list of parameter rather than a guide how  to change those parameters. Many of parameters are also not able to find in source code? Do you know where can I find the procedure to change parameters or make https, mqtts.. working?
