### ISSUE TITLE
Not to able to read data using Camel AMQP source connector using Stimzi.

### ISSUE THREAD

**Issue by iamrsaravana** [eclipse/hono#2384]
This is not an issue. i am looking for your suggestion:

I am planning to pull the data from Hono using Strimzi kafka connector (Camel AMQP source connector). I have followed the below steps to read data from Hono.

I downloaded Camel-amqp-kafka-connector from below link:

https://repo.maven.apache.org/maven2/org/apache/camel/kafkaconnector/camel-amqp-kafka-connector/0.7.0/camel-amqp-kafka-connector-0.7.0-package.tar.gz
https://downloads.apache.org/qpid/jms/0.51.0/apache-qpid-jms-0.51.0-bin.tar.gz

After downloaded the above tar and unzipped and created docker image file using below command

cat <<EOF >Dockerfile
FROM strimzi/kafka:0.20.1-kafka-2.6.0
USER root:root
RUN mkdir -p /opt/kafka/plugins/camel
COPY ./camel-activemq-kafka-connector/* /opt/kafka/plugins/camel/
USER 1001
EOF

ocker build -f ./Dockerfile -t localhost:5000/my-connector-amqp_new .
docker push localhost:5000/my-connector-amqp_new 

using below command i have created kafkaConnect( i have used my local image created above)

apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: 10.128.0.6:5000/my-connector-amqp_new
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
	

using below command to pull th data from hono message queue:

apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: camelamqpsourceconnector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: org.apache.camel.kafkaconnector.amqp.CamelAmqpSourceConnector
  tasksMax: 1
  config:
    camel.component.amqp.includeAmqpAnnotations: true
    camel.component.amqp.connectionFactory.class: org.apache.qpid.jms.JmsConnectionFactory
    camel.component.amqp.connectionFactory.remoteURI: $( kubectl get service eclipse-hono-dispatch-router-ext --output="jsonpath={.spec.clusterIP}" -n hono):15672
    camel.component.amqp.username: consumer@HONO
    camel.component.amqp.password: verysecret
    camel.component.amqp.testConnectionOnStartup: true
    camel.source.kafka.topic: mytopic
    camel.source.path.destinationType: queue
    camel.source.path.destinationName: test-queue

i am not getting any  data in my above kafka topics (mytopic)

Is there any I need to modify to get  hono payload data into  my kafka topics. I have searched various forum but I could not get any clear direction. Could you throw some light.

Thanks,
Saravanan.

**Comment by iamrsaravana** [comment]
Stimizi operator logs as follows:

2020-12-26 05:54:31 INFO  AbstractConnectOperator:436 - Reconciliation #37(timer) KafkaConnect(kafka/my-connect-cluster): creating/updating connector: camelamqpsourceconnector
**2020-12-26 05:54:31 WARN  AbstractConnectOperator:573 - Reconciliation #37(timer) KafkaConnect(kafka/my-connect-cluster): Error reconciling connector camelamqpsourceconnector**
io.strimzi.operator.cluster.operator.assembly.ConnectRestException: PUT /connectors/camelamqpsourceconnector/config returned 500 (Internal Server Error): Failed to find any class that implements Connector and which name matches org.apache.camel.kafkaconnector.amqp.CamelAmqpSourceConnector, available connectors are: PluginDesc{klass=class org.apache.camel.kafkaconnector.CamelSinkConnector, name='org.apache.camel.kafkaconnector.CamelSinkConnector', version='0.6.1', encodedVersion=0.6.1, type=sink, typeName='sink', location='file:/opt/kafka/plugins/camel/'}, PluginDesc{klass=class org.apache.camel.kafkaconnector.CamelSourceConnector, name='org.apache.camel.kafkaconnector.CamelSourceConnector', version='0.6.1', encodedVersion=0.6.1, type=source, typeName='source', location='file:/opt/kafka/plugins/camel/'}, PluginDesc{klass=class org.apache.camel.kafkaconnector.activemq.CamelActivemqSinkConnector, name='org.apache.camel.kafkaconnector.activemq.CamelActivemqSinkConnector', version='0.6.1', encodedVersion=0.6.1, type=sink, typeName='sink', location='file:/opt/kafka/plugins/camel/'}, PluginDesc{klass=class org.apache.camel.kafkaconnector.activemq.CamelActivemqSourceConnector, name='org.apache.camel.kafkaconnector.activemq.CamelActivemqSourceConnector', version='0.6.1', encodedVersion=0.6.1, type=source, typeName='source', location='file:/opt/kafka/plugins/camel/'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='2.6.0', encodedVersion=2.6.0, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='2.6.0', encodedVersion=2.6.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorCheckpointConnector, name='org.apache.kafka.connect.mirror.MirrorCheckpointConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorHeartbeatConnector, name='org.apache.kafka.connect.mirror.MirrorHeartbeatConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorSourceConnector, name='org.apache.kafka.connect.mirror.MirrorSourceConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='2.6.0', encodedVersion=2.6.0, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='2.6.0', encodedVersion=2.6.0, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='2.6.0', encodedVersion=2.6.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='2.6.0', encodedVersion=2.6.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='2.6.0', encodedVersion=2.6.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='2.6.0', encodedVersion=2.6.0, type=source, typeName='source', location='classpath'}
        at io.strimzi.operator.cluster.operator.assembly.KafkaConnectApiImpl.lambda$createOrUpdatePutRequest$1(KafkaConnectApiImpl.java:84) ~[io.strimzi.cluster-operator-0.20.1.jar:0.20.1]
        at io.vertx.core.http.impl.HttpClientResponseImpl$BodyHandler.notifyHandler(HttpClientResponseImpl.java:292) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.http.impl.HttpClientResponseImpl.lambda$bodyHandler$0(HttpClientResponseImpl.java:193) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:248) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$beginResponse$0(Http1xClientConnection.java:483) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.endResponse(Http1xClientConnection.java:502) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.access$000(Http1xClientConnection.java:241) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:641) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:601) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:575) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) [io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43) [io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229) [io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173) [io.vertx.vertx-core-3.9.1.jar:3.9.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [io.netty.netty-codec-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [io.netty.netty-codec-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) [io.netty.netty-handler-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-12-26 05:54:31 INFO  AbstractOperator:457 - Reconciliation #37(timer) KafkaConnect(kafka/my-connect-cluster): reconciled
2020-12-26 05:54:34 INFO  AbstractOperator:457 - Reconciliation #35(timer) Kafka(kafka/my-cluster): reconciled

but  **connect cluster is running without any error messages** (my-connect-cluster-connect-5c84678dd9-dhjj7). here i have attached pod/my-connect-cluster-connect-5c84678dd9-dhjj7 log file.
[my-connect-cluster-connect-5c84678dd9-dhjj7 .txt](https://github.com/eclipse/hono/files/5742742/my-connect-cluster-connect-5c84678dd9-dhjj7.txt)
