### ISSUE TITLE
LoRa Adapter crashes on startup: missing bean declaration 

### ISSUE THREAD

**Issue by fkaltner** [eclipse/hono#2436]
I guess the bean declaration for a _HttpAdapterMetrics_ bean is missing in its application configuration.

```
15:02:30.311 [main] ERROR o.e.h.a.l.i.Application$$EnhancerBySpringCGLIB$$f8610884 - exception occurred during startup, shutting down ...
java.util.concurrent.ExecutionException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'loraProtocolAdapter' defined in class path resource [org/eclipse/hono/adapter/lora/impl/Config.class]: Unsatisfied dependency expressed through method 'loraProtocolAdapter' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.eclipse.hono.client.SendMessageSampler$Factory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.eclipse.hono.service.AbstractBaseApplication.run(AbstractBaseApplication.java:161)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.eclipse.hono.adapter.lora.impl.Application.main(Application.java:37)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'loraProtocolAdapter' defined in class path resource [org/eclipse/hono/adapter/lora/impl/Config.class]: Unsatisfied dependency expressed through method 'loraProtocolAdapter' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.eclipse.hono.client.SendMessageSampler$Factory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1176)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:556)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:342)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.ObjectFactoryCreatingFactoryBean$TargetBeanObjectFactory.getObject(ObjectFactoryCreatingFactoryBean.java:153)
	at org.eclipse.hono.service.AbstractApplication.deployServiceVerticles(AbstractApplication.java:92)
	at org.eclipse.hono.service.AbstractApplication.lambda$deployVerticles$2(AbstractApplication.java:135)
	at io.vertx.core.Future.lambda$compose$3(Future.java:368)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:105)
	at io.vertx.core.impl.FutureImpl.onComplete(FutureImpl.java:83)
	at io.vertx.core.Future.compose(Future.java:364)
	at io.vertx.core.Future.compose(Future.java:336)
	at org.eclipse.hono.service.AbstractApplication.deployVerticles(AbstractApplication.java:135)
	at org.eclipse.hono.service.AbstractBaseApplication.run(AbstractBaseApplication.java:154)
	... 6 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.eclipse.hono.client.SendMessageSampler$Factory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1717)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1273)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
	... 23 common frames omitted
15:02:30.372 [main] INFO  o.e.h.a.l.i.Application$$EnhancerBySpringCGLIB$$f8610884 - shutting down application...
```

**Comment by sophokles73** [comment]
@fkaltner are you going to provide a fix?

**Comment by fkaltner** [comment]
Yes, I am on it.

**Comment by fkaltner** [comment]
This also applies to 1.5.X. Hence I also created a PR for 1.5.X.
