### ISSUE TITLE
The auth-id regular expression configuration cannot be configured separately

### ISSUE THREAD

**Issue by gongzhao2** [eclipse/hono#2559]
Hi,

We upgraded our hono from file-based version to latest version which use Mongodb as database.
Unfortunately, the auth-id of our old credentials contains the special character colon.
`"auth-id": "com.gz:gw01"`
So we cannot successfully call Hono’s credential API. When we try to get one credentials, it returns 400 status code, and device-registry report below error logs.
```
07:58:04.987 [vert.x-eventloop-thread-1] DEBUG o.e.h.s.m.c.DelegatingCredentialsManagementHttpEndpoint - getting credentials [tenant: loadtest, device-id: com.gz:gw01]]
07:58:04.988 [vert.x-eventloop-thread-1] DEBUG o.e.h.d.m.u.MongoDbDeviceRegistryUtils - Cannot construct instance of `org.eclipse.hono.service.management.credentials.PasswordCredential`, problem: authentication identifier must match pattern ^[a-zA-Z0-9-_=\.]+$
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.eclipse.hono.deviceregistry.mongodb.model.CredentialsDto["credentials"]->java.util.ArrayList[0])
java.lang.IllegalArgumentException: Cannot construct instance of `org.eclipse.hono.service.management.credentials.PasswordCredential`, problem: authentication identifier must match pattern ^[a-zA-Z0-9-_=\.]+$
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.eclipse.hono.deviceregistry.mongodb.model.CredentialsDto["credentials"]->java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4236)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4167)
        at io.vertx.core.json.jackson.JacksonCodec.fromValue(JacksonCodec.java:40)
        at io.vertx.core.json.JsonObject.mapTo(JsonObject.java:124)
        at org.eclipse.hono.deviceregistry.mongodb.service.MongoDbBasedCredentialsService.lambda$getCredentialsDto$11(MongoDbBasedCredentialsService.java:370)
        at java.base/java.util.Optional.map(Unknown Source)
        at org.eclipse.hono.deviceregistry.mongodb.service.MongoDbBasedCredentialsService.lambda$getCredentialsDto$13(MongoDbBasedCredentialsService.java:370)
        at io.vertx.core.Future.lambda$compose$3(Future.java:368)
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:105)
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:150)
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:111)
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:176)
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21)
        at io.vertx.ext.mongo.impl.MongoClientImpl.lambda$null$12(MongoClientImpl.java:795)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.eclipse.hono.service.management.credentials.PasswordCredential`, problem: authentication identifier must match pattern ^[a-zA-Z0-9-_=\.]+$
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.eclipse.hono.deviceregistry.mongodb.model.CredentialsDto["credentials"]->java.util.ArrayList[0])
```

Then I find there don't have "HONO_REGISTRY_HTTP_AUTH_ID_PATTERN" such parameter in place,  "REGEX_AUTH_ID"  is write to this file `services/device-registry-base/src/main/java/org/eclipse/hono/service/management/credentials/PasswordCredential.java`  
```
public static final String REGEX_AUTH_ID = "^[a-zA-Z0-9-_=\\.]+$";
```

Why can't the user configure this "AUTH_ID_PATTERN" separately?

**Comment by gongzhao2** [comment]
Wouldn't it be better if this parameter "REGEX_AUTH_ID" can be replaced with the corresponding variable?

**Comment by kaniyan** [comment]
@gongzhao2 IMHO having colon in `auth-id` doesn't sound like a good practice to me as colon is commonly used as password delimiter in many protocols.

@sophokles73 I found this PR #2223 for removing the `auth-id` regex pattern from API. It seems to be that we intentionally don't want to support that anymore and in case of `PasswordCredential` we accept ids that confirm to the regex `^[a-zA-Z0-9-_=\\.]+$`.  Would you mind throwing some light on this?

**Comment by sophokles73** [comment]
Well, it didn't seem to make much sense to statically define the pattern in the Management API because it should actually be a property of the registry implementation. We defined it as a constant because at that time nobody bothered about setting a different pattern.
However, making the pattern configurable by means of an environment variable of the registry sounds like a good idea as the policy for identifiers should probably be a concern of the organization running the registry (as in this case).
We would be glad to accept a corresponding PR :-)
