### ISSUE TITLE
Unit test org.eclipse.hono.client.kafka.consumer.AsyncHandlingAutoCommitKafkaConsumerTest is flaky

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#2686]
The *testConsumerCommitsOffsetsOfSkippedExpiredRecords* test case sometimes fails in our CI build with
```bash
Error:  testConsumerCommitsOffsetsOfSkippedExpiredRecords{VertxTestContext}  Time elapsed: 0.056 s  <<< FAILURE!
java.lang.AssertionError: 
org.opentest4j.AssertionFailedError: 
expected: 6L
but was : 5L
	at org.eclipse.hono.client.kafka.consumer.AsyncHandlingAutoCommitKafkaConsumerTest.lambda$testConsumerCommitsOffsetsOfSkippedExpiredRecords$42(AsyncHandlingAutoCommitKafkaConsumerTest.java:492)
	at org.eclipse.hono.client.kafka.consumer.AsyncHandlingAutoCommitKafkaConsumerTest.lambda$testConsumerCommitsOffsetsOfSkippedExpiredRecords$43(AsyncHandlingAutoCommitKafkaConsumerTest.java:489)
```

**Comment by calohmn** [comment]
Fixed via 1807142c8fef3049d4ddc2c6a331e0f372e45ff1.
