### ISSUE TITLE
ConcurrentModificationException in Command Router

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2745]
This has appeared in log output of a Command Router container:
````
io.vertx.core.impl.ContextImpl Unhandled exception
java.util.ConcurrentModificationException: null
	at java.base/java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
	at java.base/java.util.LinkedList$ListItr.next(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at org.eclipse.hono.commandrouter.impl.kafka.KafkaCommandProcessingQueue$TopicPartitionCommandQueue.markAsUnusedAndClear(KafkaCommandProcessingQueue.java:199)
	at org.eclipse.hono.commandrouter.impl.kafka.KafkaCommandProcessingQueue.setCurrentlyHandledPartitions(KafkaCommandProcessingQueue.java:140)
	at org.eclipse.hono.commandrouter.impl.kafka.KafkaBasedCommandConsumerFactoryImpl.lambda$start$0(KafkaBasedCommandConsumerFactoryImpl.java:119)
	at org.eclipse.hono.client.kafka.consumer.HonoKafkaConsumer$1.lambda$onPartitionsAssigned$1(HonoKafkaConsumer.java:333)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
````

**Comment by calohmn** [comment]
The cause of the exception is that `queue.remove(item)` gets called from inside the `queue` iteration code (via failing the sendAction promise):
````
at org.eclipse.hono.commandrouter.impl.kafka.KafkaCommandProcessingQueue$TopicPartitionCommandQueue.remove(KafkaCommandProcessingQueue.java:184)
at org.eclipse.hono.commandrouter.impl.kafka.KafkaCommandProcessingQueue.lambda$remove$1(KafkaCommandProcessingQueue.java:94)
at java.base/java.util.Optional.ifPresent(Optional.java:183)
at org.eclipse.hono.commandrouter.impl.kafka.KafkaCommandProcessingQueue.remove(KafkaCommandProcessingQueue.java:94)
at org.eclipse.hono.commandrouter.impl.kafka.KafkaBasedMappingAndDelegatingCommandHandler.lambda$mapAndDelegateIncomingCommandMessage$0(KafkaBasedMappingAndDelegatingCommandHandler.java:114)
at io.vertx.core.Future.lambda$onFailure$1(Future.java:166)
at io.vertx.core.impl.FutureImpl$Handlers.handle(FutureImpl.java:228)
at io.vertx.core.impl.FutureImpl$Handlers.handle(FutureImpl.java:224)
at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:125)
at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178)
at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21)
at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:125)
at org.eclipse.hono.commandrouter.impl.kafka.KafkaCommandProcessingQueue$TopicPartitionCommandQueue.lambda$markAsUnusedAndClear$0(KafkaCommandProcessingQueue.java:211)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at org.eclipse.hono.commandrouter.impl.kafka.KafkaCommandProcessingQueue$TopicPartitionCommandQueue.markAsUnusedAndClear(KafkaCommandProcessingQueue.java:203)
at org.eclipse.hono.commandrouter.impl.kafka.KafkaCommandProcessingQueue.setCurrentlyHandledPartitions(KafkaCommandProcessingQueue.java:141)
````

**Comment by sophokles73** [comment]
@calohmn does this also affect 1.8.x?

**Comment by calohmn** [comment]
@sophokles73 yes, I'll apply the fix for 1.8.x as well.

**Comment by sophokles73** [comment]
@calohmn can you also add an entry to the release notes?

**Comment by calohmn** [comment]
@sophokles73 yes, I've added an entry.
