### ISSUE TITLE
IllegalStateException: You can only check the position for partitions assigned to this consumer

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2803]
This exception was observed a few times in command router component logs:
```
[vert.x-kafka-consumer-thread-0] ERROR AsyncHandlingAutoCommitKafkaConsumer error fetching positions for 1 assigned partitions
java.lang.IllegalStateException: You can only check the position for partitions assigned to this consumer.
	at org.apache.kafka.clients.consumer.KafkaConsumer.position(KafkaConsumer.java:1751)
	at org.apache.kafka.clients.consumer.KafkaConsumer.position(KafkaConsumer.java:1718)
	at org.eclipse.hono.client.kafka.consumer.HonoKafkaConsumer.lambda$ensurePositionsHaveBeenSetIfNeeded$7(HonoKafkaConsumer.java:360)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at org.eclipse.hono.client.kafka.consumer.HonoKafkaConsumer.lambda$ensurePositionsHaveBeenSetIfNeeded$9(HonoKafkaConsumer.java:360)
	at org.eclipse.hono.client.kafka.consumer.HonoKafkaConsumer.lambda$runOnKafkaWorkerThread$20(HonoKafkaConsumer.java:593)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by calohmn** [comment]
The changes made here now mean that seemingly not necessarily _all_ fetch positions get determined as part of the `ensurePositionsHaveBeenSetIfNeeded()` method, meaning the `start()` method may complete before all positions got set.

**Comment by calohmn** [comment]
Reverted the optimization made in 036116829083acc2cb5cca71fcb2cd11478984c5, now invoking the `position()` method again for all new partitions  (see 2c159e75b2c5ce9ec2c545f034683aa8ac19c41a).
