### ISSUE TITLE
MongoDb Registry throws Duplicate Key Error when setting a tenant's trusted-ca field to an empty array

### ISSUE THREAD

**Issue by fkaltner** [eclipse/hono#2819]
1. Create a tenant (including a trusted-ca) "a"
2. Create another  (including a trusted-ca) tenant "b"
3. Remove the trusted-ca by setting the property to an empty array (`"trusted-ca" : [ ]`) in tenant "a" by a HTTP PUT
4. If this is the first tenant on your installation the PUT will succeed, if not repeat the step for tenant "b"

The exception I observed in the log is:

```
2021-08-10 08:47:53.466 [vert.x-eventloop-thread-3] DEBUG o.e.h.s.m.t.DelegatingTenantManagementHttpEndpoint - updating tenant [tst_cf49e0ddb49a4b739ae356265e337385]
2021-08-10 08:47:53.468 [vert.x-eventloop-thread-3] DEBUG o.e.h.d.m.m.MongoDbBasedTenantDao - conflict updating tenant [tst_cf49e0ddb49a4b739ae356265e337385]. An existing tenant uses a certificate authority with the same Subject DN
com.mongodb.MongoCommandException: Command failed with error 11000 (DuplicateKey): 'E11000 duplicate key error collection: iothub.hub-tenants index: tenant.trusted-ca.subject-dn_1 dup key: { tenant.trusted-ca.subject-dn: null }' on server mongodb.hono:27017. The full response is {"ok": 0.0, "errmsg": "E11000 duplicate key error collection: iothub.hub-tenants index: tenant.trusted-ca.subject-dn_1 dup key: { tenant.trusted-ca.subject-dn: null }", "code": 11000, "codeName": "DuplicateKey", "keyPattern": {"tenant.trusted-ca.subject-dn": 1}, "keyValue": {"tenant.trusted-ca.subject-dn": null}}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:179)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:386)
	at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:372)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:667)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:634)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:510)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:507)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Unknown Source)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implRead(Unknown Source)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(Unknown Source)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.read(Unknown Source)
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.read(AsynchronousSocketChannelStream.java:137)
	at com.mongodb.internal.connection.AsynchronousChannelStream.readAsync(AsynchronousChannelStream.java:105)
	at com.mongodb.internal.connection.InternalStreamConnection.readAsync(InternalStreamConnection.java:507)
	at com.mongodb.internal.connection.InternalStreamConnection.access$1000(InternalStreamConnection.java:74)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:624)
	at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback.onResult(InternalStreamConnection.java:609)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:510)
	at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:507)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(Unknown Source)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(Unknown Source)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(Unknown Source)
	at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(Unknown Source)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-08-10 08:47:53.469 [vert.x-eventloop-thread-3] DEBUG o.e.h.d.util.DeviceRegistryUtils - an existing tenant uses a certificate authority with the same Subject DN
org.eclipse.hono.client.ClientErrorException: an existing tenant uses a certificate authority with the same Subject DN
	at org.eclipse.hono.deviceregistry.mongodb.model.MongoDbBasedTenantDao.lambda$update$15(MongoDbBasedTenantDao.java:324)
	at io.vertx.core.Future.lambda$recover$6(Future.java:499)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21)
	at io.vertx.core.impl.FailedFuture.onComplete(FailedFuture.java:49)
	at io.vertx.core.Future.lambda$compose$3(Future.java:382)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21)
	at io.vertx.ext.mongo.impl.MongoClientImpl.lambda$null$19(MongoClientImpl.java:859)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Note that by removing the "trusted-ca" field in the payload of the PUT request this actually is working. However, since it is quite likely that somebody may set this to an empty array, I think we should fix this (e.g. by removing the field internally if it is set to an empty array).

**Comment by sophokles73** [comment]
So, your point seems to be that it should be perfectly fine for two tenants to contain an empty array of CAs, right? If so, I agree.

**Comment by fkaltner** [comment]
Yes, that's exactly what I wanted to say 😄
