### ISSUE TITLE
[Hono-MQTT-Adapter] no credit available for sending request

### ISSUE THREAD

**Issue by gongzhao2** [eclipse/hono#2885]
Hello,

**Version**
Hono: 1.10.0
Kubernetes Version: v1.15.6

**Description**
We deploy 1.10.0 version of Hono on Kubernetes cluster.
```
$ kubectl get pods
NAME                                                READY   STATUS    RESTARTS   AGE
hono-test-adapter-mqtt-vertx-6fb876676-g9wqx        1/1     Running   0          55m
hono-test-service-auth-9769ffc68-8zv5r              1/1     Running   0          3h57m
hono-test-service-command-router-6f48c7c55d-8clg8   1/1     Running   0          3h57m
hono-test-service-device-registry-6f494b675-88hrc   1/1     Running   0          96m
```
we use enmasse as message broker, below is enmasse's address:
```
$ kubectl get address -n enmasse-test
NAME                                  ADDRESS                     READY   PHASE    AGE
hono-test.command-internal            command_internal            true    Active   11d
hono-test.command-response.loadtest   command_response/loadtest   true    Active   11d
hono-test.command-router.loadtest     cmd_router/loadtest         true    Active   3h49m
hono-test.command.loadtest            command/loadtest            true    Active   2d2h
hono-test.event.loadtest              event/loadtest              true    Active   11d
hono-test.telemetry.loadtest          telemetry/loadtest          true    Active   11d
```

Then we want to do loadtest against Hono via MQTT protocol(**gateway mode**).
So we use [mqtt-jmeter](https://github.com/xmeter-net/mqtt-jmeter) to do some test. 
1. At first I register 1 gateway device and corresponding credentials.
2. Then I register 1000 edge device.
3. Configure Jmeter script to start test

Gateway Device:
```
$ curl https://******/v1/devices/loadtest/com.test:gateway001
{
    "enabled": true,
    "status": {
        "updated": "2021-10-09T17:17:21Z"
    }
}
```
One Edge Device:
```
$ curl https://******/v1/devices/loadtest/com.test:device_1
{
    "enabled": true,
    "via": [
        "com.test:gateway001"
    ],
    "status": {
        "created": "2021-10-11T07:33:44Z"
    }
}
```

But If the mqtt client (the number of jmeter threads) exceeds a certain number (perhaps 200), the MQTT adapter will report the following error:
```
10:21:37.690 [vert.x-eventloop-thread-1] DEBUG o.e.h.c.amqp.RequestResponseClient - cannot send request to peer, no credit left for link [link target: credentials/loadtest]
10:21:37.690 [vert.x-eventloop-thread-1] DEBUG o.e.h.a.m.i.VertxBasedMqttProtocolAdapter - device authentication or early stage checks failed
org.eclipse.hono.client.ServerErrorException: no credit available for sending request
        at org.eclipse.hono.client.amqp.RequestResponseClient.lambda$sendRequest$8(RequestResponseClient.java:623)
        at org.eclipse.hono.util.HonoProtonHelper.executeOnContext(HonoProtonHelper.java:230)
        at org.eclipse.hono.client.impl.HonoConnectionImpl.executeOnContext(HonoConnectionImpl.java:235)
        at org.eclipse.hono.client.amqp.RequestResponseClient.sendRequest(RequestResponseClient.java:618)
        at org.eclipse.hono.client.amqp.RequestResponseClient.createAndSendRequest(RequestResponseClient.java:581)
        at org.eclipse.hono.client.amqp.RequestResponseClient.createAndSendRequest(RequestResponseClient.java:530)
        at org.eclipse.hono.client.amqp.RequestResponseClient.createAndSendRequest(RequestResponseClient.java:484)
        at org.eclipse.hono.client.registry.amqp.ProtonBasedCredentialsClient.lambda$get$3(ProtonBasedCredentialsClient.java:191)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
        at org.eclipse.hono.client.impl.CachingClientFactory.getOrCreateClient(CachingClientFactory.java:163)
        at org.eclipse.hono.client.impl.CachingClientFactory.lambda$getOrCreateClient$3(CachingClientFactory.java:211)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:952)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:919)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
        at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
        at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:942)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
10:21:37.690 [vert.x-eventloop-thread-1] DEBUG o.e.h.a.m.i.VertxBasedMqttProtocolAdapter - rejecting connection request from client [clientId: device_415], cause:
org.eclipse.hono.client.ServerErrorException: no credit available for sending request
        at org.eclipse.hono.client.amqp.RequestResponseClient.lambda$sendRequest$8(RequestResponseClient.java:623)
        at org.eclipse.hono.util.HonoProtonHelper.executeOnContext(HonoProtonHelper.java:230)
        at org.eclipse.hono.client.impl.HonoConnectionImpl.executeOnContext(HonoConnectionImpl.java:235)
        at org.eclipse.hono.client.amqp.RequestResponseClient.sendRequest(RequestResponseClient.java:618)
        at org.eclipse.hono.client.amqp.RequestResponseClient.createAndSendRequest(RequestResponseClient.java:581)
        at org.eclipse.hono.client.amqp.RequestResponseClient.createAndSendRequest(RequestResponseClient.java:530)
        at org.eclipse.hono.client.amqp.RequestResponseClient.createAndSendRequest(RequestResponseClient.java:484)
        at org.eclipse.hono.client.registry.amqp.ProtonBasedCredentialsClient.lambda$get$3(ProtonBasedCredentialsClient.java:191)
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
        at org.eclipse.hono.client.impl.CachingClientFactory.getOrCreateClient(CachingClientFactory.java:163)
        at org.eclipse.hono.client.impl.CachingClientFactory.lambda$getOrCreateClient$3(CachingClientFactory.java:211)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:952)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:919)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
        at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
        at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:942)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
10:21:37.690 [vert.x-eventloop-thread-1] DEBUG o.e.h.c.impl.CachingClientFactory - reusing cached client [credentials-loadtest]
10:21:37.690 [vert.x-eventloop-thread-1] DEBUG o.e.h.c.amqp.RequestResponseClient - cannot send request to peer, no credit left for link [link target: credentials/loadtest]
10:21:37.691 [vert.x-eventloop-thread-1] DEBUG o.e.h.a.m.i.VertxBasedMqttProtocolAdapter - device authentication or early stage checks failed
org.eclipse.hono.client.ServerErrorException: no credit available for sending request
```

**What did I do**
I insert below parameters into device-registry as environment variables:
```
  HONO_CREDENTIALS_SVC_RECEIVERLINKCREDIT: "100000"
  HONO_REGISTRY_SVC_RECEIVERLINKCREDIT: "100000"
  HONO_TENANT_SVC_RECEIVERLINKCREDIT: "100000"
```
But still doesn't work.

**Expected result**
How can we configure the number of credits for credentials client so that we can support more than 200 MQTT client in gateway mode?

**Comment by gongzhao2** [comment]
I configured above configmap in helm chart:

**values.yaml**
```
adapters:
  mqtt:
    envConfigMap: hono-mqtt-env-configmap
...
deviceRegistryExample:
  mongoDBBasedDeviceRegistry:
    envConfigMap: hono-device-registry-env-configmap
```

These environment variables are indeed effective in the pod, I can view it when I enter the pod
```
$ kubectl exec -ti hono-test-service-device-registry-6f494b675-88hrc /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@hono-test-service-device-registry-6f494b675-88hrc:/# echo $HONO_CREDENTIALS_SVC_RECEIVERLINKCREDIT
100000
root@hono-test-service-device-registry-6f494b675-88hrc:/# echo $HONO_REGISTRY_SVC_USERNAMEPATTERN
^[a-zA-Z0-9-_\.\:]+$
root@hono-test-service-device-registry-6f494b675-88hrc:/# exit
exit
$ kubectl exec -ti hono-test-adapter-mqtt-vertx-6fb876676-g9wqx /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@hono-test-adapter-mqtt-vertx-6fb876676-g9wqx:/# echo $HONO_CREDENTIALS_INITIALCREDITS
100000
root@hono-test-adapter-mqtt-vertx-6fb876676-g9wqx:/# exit
exit
```

**Comment by sophokles73** [comment]
> I need an MQTT gateway to forward messages. I will create a new MQTT Broker to complete this test

Not sure why you need an MQTT broker for this ...

**Comment by gongzhao2** [comment]
> 
> 
> > I need an MQTT gateway to forward messages. I will create a new MQTT Broker to complete this test
> 
> Not sure why you need an MQTT broker for this ...

I mean I need a MQTT gateway to foward messages.
