### ISSUE TITLE
Flaky AsyncHandlingAutoCommitKafkaConsumerTest#testConsumerCommitsInitialOffset unit test

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2916]
The test `AsyncHandlingAutoCommitKafkaConsumerTest#testConsumerCommitsInitialOffset` fails sometimes:
```
Error:  Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.542 s <<< FAILURE! - in org.eclipse.hono.client.kafka.consumer.AsyncHandlingAutoCommitKafkaConsumerTest
Error:  testConsumerCommitsInitialOffset{VertxTestContext}  Time elapsed: 0.103 s  <<< FAILURE!
java.lang.AssertionError: expected not to be: null
	at org.eclipse.hono.client.kafka.consumer.AsyncHandlingAutoCommitKafkaConsumerTest.lambda$testConsumerCommitsInitialOffset$54(AsyncHandlingAutoCommitKafkaConsumerTest.java:608)
	at org.eclipse.hono.client.kafka.consumer.AsyncHandlingAutoCommitKafkaConsumerTest.lambda$testConsumerCommitsInitialOffset$55(AsyncHandlingAutoCommitKafkaConsumerTest.java:604)
```
Test should be fixed or replaced with a corresponding integration tests (similar to tests in `HonoKafkaConsumerIT`).

**Comment by calohmn** [comment]
Fixed via 15f785c8c7dcc0cf0ddbf80d6e1b9eea40bdce30.
