### ISSUE TITLE
Use timeout for command processing in Command Router

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2919]
When the Command Router receives and processes a command message, there are Infinispan requests being done (concerning the `device-connection` cache). Currently there is no timeout getting applied on this.
That means when Infinispan requests take a long time, the whole command processing is getting impacted, in the end triggering the mechanism that limits the number of command records processed in parallel and pausing the Kafka consumer then (if Kafka messaging is used).

There should be a configurable timeout that limits the command processing time.

**Comment by calohmn** [comment]
A scenario where the Infinispan Hot Rot client request gets stuck seems to involve an NPE in the Hot Rot client - see [ISPN-13480](https://issues.redhat.com/browse/ISPN-13480).
```
java.lang.NullPointerException: null
	at org.infinispan.client.hotrod.impl.transport.netty.ChannelPool.acquire(ChannelPool.java:77)
	at org.infinispan.client.hotrod.impl.transport.netty.ChannelFactory.fetchChannelAndInvoke(ChannelFactory.java:270)
	at org.infinispan.client.hotrod.impl.transport.netty.ChannelFactory.fetchChannelAndInvoke(ChannelFactory.java:324)
	at org.infinispan.client.hotrod.impl.operations.AbstractKeyOperation.fetchChannelAndInvoke(AbstractKeyOperation.java:41)
	at org.infinispan.client.hotrod.impl.operations.RetryOnFailureOperation.execute(RetryOnFailureOperation.java:61)
	at org.infinispan.client.hotrod.impl.RemoteCacheImpl.getAsync(RemoteCacheImpl.java:561)
	at org.eclipse.hono.deviceconnection.infinispan.client.BasicCache.lambda$get$9(BasicCache.java:194)
	at org.eclipse.hono.deviceconnection.infinispan.client.BasicCache.lambda$withCache$2(BasicCache.java:131)
	at org.eclipse.hono.util.Futures.create(Futures.java:49)
	at org.eclipse.hono.deviceconnection.infinispan.client.BasicCache.lambda$withCache$3(BasicCache.java:131)
	at java.base/java.util.Optional.map(Unknown Source)
	at org.eclipse.hono.deviceconnection.infinispan.client.BasicCache.withCache(BasicCache.java:131)
	at org.eclipse.hono.deviceconnection.infinispan.client.BasicCache.get(BasicCache.java:194)
	at org.eclipse.hono.deviceconnection.infinispan.client.CacheBasedDeviceConnectionInfo.getCommandHandlingAdapterInstances(CacheBasedDeviceConnectionInfo.java:256)
	at org.eclipse.hono.commandrouter.impl.CommandTargetMapperImpl.lambda$getTargetGatewayAndAdapterInstance$2(CommandTargetMapperImpl.java:96)
```

**Comment by calohmn** [comment]
Concerning the above Hot Rod client NPE: 
configuring `connectionPoolMaxPendingRequests` in the Hot Rod client properties seems to help here - with that configuration, a few subsequent tests haven't shown the exception again.
