### ISSUE TITLE
Handle exception when creating Kafka clients

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#2953]
When deploying the Hono Helm chart, with the deployment of Kafka included, the protocol adapters may find the Kafka bootstrap server URLs to be non-resolvable initially, because it takes a while for Kafka to become ready.

Currently, the protocol adapters will shut down directly if encountering such a `ConfigException: No resolvable bootstrap urls given in bootstrap.servers` exception when creating the Kafka clients.
It would be better to retry the Kafka client creation, similar to the retries concerning the AMQP messaging network connection.

Log excerpt:
```
14:16:36.869 [main] INFO  o.a.k.c.admin.AdminClientConfig - AdminClientConfig values: 
	bootstrap.servers = [eclipse-hono-kafka-0.eclipse-hono-kafka-headless.hono:9094]
[...]

14:16:37.173 [main] WARN  org.apache.kafka.clients.ClientUtils - Couldn't resolve server eclipse-hono-kafka-0.eclipse-hono-kafka-headless.hono:9094 from bootstrap.servers as DNS resolution failed for eclipse-hono-kafka-0.eclipse-hono-kafka-headless.hono
14:16:37.198 [main] ERROR o.e.h.a.m.s.Application$$EnhancerBySpringCGLIB$$bb91eb70 - exception occurred during startup, shutting down ...
java.util.concurrent.ExecutionException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vertxBasedMqttProtocolAdapter' defined in org.eclipse.hono.adapter.mqtt.spring.Config: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.eclipse.hono.adapter.mqtt.impl.VertxBasedMqttProtocolAdapter]: Factory method 'vertxBasedMqttProtocolAdapter' threw exception; nested exception is org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.eclipse.hono.service.spring.AbstractBaseApplication.run(AbstractBaseApplication.java:169)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:782)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:772)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at org.eclipse.hono.adapter.mqtt.spring.Application.main(Application.java:37)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vertxBasedMqttProtocolAdapter' defined in org.eclipse.hono.adapter.mqtt.spring.Config: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.eclipse.hono.adapter.mqtt.impl.VertxBasedMqttProtocolAdapter]: Factory method 'vertxBasedMqttProtocolAdapter' threw exception; nested exception is org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:353)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.ObjectFactoryCreatingFactoryBean$TargetBeanObjectFactory.getObject(ObjectFactoryCreatingFactoryBean.java:153)
	at org.eclipse.hono.service.spring.AbstractApplication.deployServiceVerticles(AbstractApplication.java:103)
	at org.eclipse.hono.service.spring.AbstractApplication.lambda$deployVerticles$1(AbstractApplication.java:69)
	at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:196)
	at io.vertx.core.impl.future.FutureBase.compose(FutureBase.java:84)
	at io.vertx.core.Future.compose(Future.java:199)
	at org.eclipse.hono.service.spring.AbstractApplication.deployVerticles(AbstractApplication.java:69)
	at org.eclipse.hono.service.spring.AbstractBaseApplication.run(AbstractBaseApplication.java:162)
	... 6 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.eclipse.hono.adapter.mqtt.impl.VertxBasedMqttProtocolAdapter]: Factory method 'vertxBasedMqttProtocolAdapter' threw exception; nested exception is org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 23 common frames omitted
Caused by: org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:540)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:144)
	at org.eclipse.hono.client.command.kafka.KafkaBasedInternalCommandConsumer.<init>(KafkaBasedInternalCommandConsumer.java:125)
	at org.eclipse.hono.adapter.spring.AbstractAdapterConfig.lambda$setCollaborators$1(AbstractAdapterConfig.java:166)
	at org.eclipse.hono.client.command.CommandRouterCommandConsumerFactory.registerInternalCommandConsumer(CommandRouterCommandConsumerFactory.java:118)
	at org.eclipse.hono.adapter.spring.AbstractAdapterConfig.setCollaborators(AbstractAdapterConfig.java:164)
	at org.eclipse.hono.adapter.mqtt.spring.Config.vertxBasedMqttProtocolAdapter(Config.java:61)
	at org.eclipse.hono.adapter.mqtt.spring.Config$$EnhancerBySpringCGLIB$$dfe9f518.CGLIB$vertxBasedMqttProtocolAdapter$6(<generated>)
	at org.eclipse.hono.adapter.mqtt.spring.Config$$EnhancerBySpringCGLIB$$dfe9f518$$FastClassBySpringCGLIB$$a6264038.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.eclipse.hono.adapter.mqtt.spring.Config$$EnhancerBySpringCGLIB$$dfe9f518.vertxBasedMqttProtocolAdapter(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 24 common frames omitted
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:89)
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:48)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:494)
	... 40 common frames omitted
14:16:37.203 [main] INFO  o.e.h.a.m.s.Application$$EnhancerBySpringCGLIB$$bb91eb70 - shutting down application...
14:16:37.211 [main] INFO  o.e.h.a.m.s.Application$$EnhancerBySpringCGLIB$$bb91eb70 - closing vert.x instance ...
14:16:37.291 [main] INFO  o.e.h.a.m.s.Application$$EnhancerBySpringCGLIB$$bb91eb70 - application has been shut down successfully
14:16:38.298 [SpringApplicationShutdownHook] INFO  o.e.h.a.m.s.Application$$EnhancerBySpringCGLIB$$bb91eb70 - shutting down application...
14:16:38.299 [SpringApplicationShutdownHook] INFO  o.e.h.a.m.s.Application$$EnhancerBySpringCGLIB$$bb91eb70 - closing vert.x instance ...
14:16:38.299 [SpringApplicationShutdownHook] INFO  o.e.h.a.m.s.Application$$EnhancerBySpringCGLIB$$bb91eb70 - application has been shut down successfully
```

**Comment by sophokles73** [comment]
Would the Kafka client automatically continue trying to resolve the host name(s) and connect to the cluster if we would not stop the adapter?

**Comment by calohmn** [comment]
There is no Kafka client object here, which could do that, because the exception is thrown when trying to create the Kafka client.

When the client creation succeeds, it will then do automatic reconnects in case of lost connections.

**Comment by calohmn** [comment]
<details>
<summary>Here a stacktrace concerning a failure to create a producer.</summary>

~~~
13:28:56.811 [main] ERROR o.e.h.a.l.i.Application$$EnhancerBySpringCGLIB$$303707f6 - exception occurred during startup, shutting down ...
java.util.concurrent.ExecutionException: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.eclipse.hono.service.spring.AbstractBaseApplication.run(AbstractBaseApplication.java:169)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:782)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:772)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at org.eclipse.hono.adapter.lora.impl.Application.main(Application.java:37)
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:440)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:291)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:274)
	at io.vertx.kafka.client.producer.KafkaWriteStream.create(KafkaWriteStream.java:103)
	at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.lambda$createShared$1(KafkaProducerImpl.java:57)
	at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.lambda$createShared$9(KafkaProducerImpl.java:104)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.createShared(KafkaProducerImpl.java:103)
	at io.vertx.kafka.client.producer.impl.KafkaProducerImpl.createShared(KafkaProducerImpl.java:57)
	at io.vertx.kafka.client.producer.KafkaProducer.createShared(KafkaProducer.java:68)
	at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.lambda$sharedFactory$0(CachingKafkaProducerFactory.java:91)
	at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.lambda$getOrCreateProducer$2(CachingKafkaProducerFactory.java:162)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at org.eclipse.hono.client.kafka.producer.CachingKafkaProducerFactory.getOrCreateProducer(CachingKafkaProducerFactory.java:159)
	at org.eclipse.hono.client.kafka.producer.AbstractKafkaBasedMessageSender.getOrCreateProducer(AbstractKafkaBasedMessageSender.java:290)
	at org.eclipse.hono.client.kafka.producer.AbstractKafkaBasedMessageSender.start(AbstractKafkaBasedMessageSender.java:106)
	at org.eclipse.hono.client.util.MessagingClientProvider.lambda$start$8(MessagingClientProvider.java:175)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.eclipse.hono.client.util.MessagingClientProvider.start(MessagingClientProvider.java:176)
	at org.eclipse.hono.adapter.MessagingClientProviders.start(MessagingClientProviders.java:145)
	at org.eclipse.hono.adapter.AbstractProtocolAdapterBase.startInternal(AbstractProtocolAdapterBase.java:341)
	at org.eclipse.hono.service.AbstractServiceBase.start(AbstractServiceBase.java:93)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:89)
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:48)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:414)
	... 38 common frames omitted
13:28:56.811 [main] INFO  o.e.h.a.l.i.Application$$EnhancerBySpringCGLIB$$303707f6 - shutting down application...
~~~

</details>
