### ISSUE TITLE
Quarkus based images do not work with BoringSSL

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#3107]
The instructions given in [Using OpenSSL](https://www.eclipse.org/hono/docs/admin-guide/secure_communication/#using-openssl) do not work with the Quarkus based images.
When starting up a container that contains the BoringSSL jar file in `/opt/hono/extensions`, the shared library cannot be loaded:
```sh
HTTP2022-02-24 06:43:37,771 DEBUG [io.net.han.ssl.OpenSsl] (vert.x-eventloop-thread-2) Failed to load netty-tcnative; OpenSslEngine will be unavailable, unless the application has already loaded the symbols by some other means. See https://netty.io/wiki/forked-tomcat-native.html for more information.: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]
HTTP	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:114)
HTTP	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:705)
HTTP	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:146)
HTTP	at org.eclipse.hono.connection.impl.ConnectionFactoryImpl.addTlsTrustOptions(ConnectionFactoryImpl.java:383)
HTTP	at org.eclipse.hono.connection.impl.ConnectionFactoryImpl.addOptions(ConnectionFactoryImpl.java:360)
HTTP	at org.eclipse.hono.connection.impl.ConnectionFactoryImpl.connect(ConnectionFactoryImpl.java:144)
HTTP	at org.eclipse.hono.client.impl.HonoConnectionImpl$ConnectionAttempt.connect(HonoConnectionImpl.java:1096)
HTTP	at org.eclipse.hono.client.impl.HonoConnectionImpl$ConnectionAttempt.start(HonoConnectionImpl.java:1059)
HTTP	at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$connect$2(HonoConnectionImpl.java:387)
HTTP	at org.eclipse.hono.util.HonoProtonHelper.executeOnContext(HonoProtonHelper.java:230)
HTTP	at org.eclipse.hono.client.impl.HonoConnectionImpl.executeOnContext(HonoConnectionImpl.java:236)
HTTP	at org.eclipse.hono.client.impl.HonoConnectionImpl.connect(HonoConnectionImpl.java:377)
HTTP	at org.eclipse.hono.client.impl.HonoConnectionImpl.connect(HonoConnectionImpl.java:358)
HTTP	at org.eclipse.hono.client.impl.HonoConnectionImpl.connect(HonoConnectionImpl.java:352)
HTTP	at org.eclipse.hono.client.amqp.AbstractServiceClient.start(AbstractServiceClient.java:274)
HTTP	at org.eclipse.hono.client.notification.amqp.ProtonBasedNotificationReceiver.start(ProtonBasedNotificationReceiver.java:77)
HTTP	at org.eclipse.hono.util.WrappedLifecycleComponentVerticle.start(WrappedLifecycleComponentVerticle.java:41)
HTTP	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
HTTP	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
HTTP	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
HTTP	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
HTTP	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
HTTP	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
HTTP	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
HTTP	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
HTTP	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
HTTP	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
HTTP	at java.base/java.lang.Thread.run(Unknown Source)
HTTP	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_x86_64
HTTP		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:224)
HTTP		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
HTTP		... 27 more
HTTP	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_x86_64.so
HTTP		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:171)
HTTP		... 28 more
HTTP		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
HTTP			at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
HTTP			at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
HTTP			at java.base/java.lang.System.loadLibrary(Unknown Source)
HTTP			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
HTTP			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:376)
HTTP			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:146)
HTTP			... 28 more
HTTP			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
HTTP				at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
HTTP				at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
HTTP				at java.base/java.lang.System.loadLibrary(Unknown Source)
HTTP				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
HTTP				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
HTTP				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
HTTP				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
HTTP				at java.base/java.lang.reflect.Method.invoke(Unknown Source)
HTTP				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:410)
HTTP				at java.base/java.security.AccessController.doPrivileged(Unknown Source)
HTTP				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:402)
HTTP				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:368)
HTTP				... 29 more
HTTP	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_x86_64_fedora
HTTP		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:224)
HTTP		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
HTTP		... 27 more
HTTP	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_x86_64_fedora.so
HTTP		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:171)
HTTP		... 28 more
HTTP		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64_fedora in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
HTTP			at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
HTTP			at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
HTTP			at java.base/java.lang.System.loadLibrary(Unknown Source)
HTTP			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
HTTP			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:376)
HTTP			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:146)
HTTP			... 28 more
HTTP			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64_fedora in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
HTTP				at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
HTTP				at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
HTTP				at java.base/java.lang.System.loadLibrary(Unknown Source)
HTTP				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
HTTP				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
HTTP				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
HTTP				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
HTTP				at java.base/java.lang.reflect.Method.invoke(Unknown Source)
HTTP				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:410)
HTTP				at java.base/java.security.AccessController.doPrivileged(Unknown Source)
HTTP				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:402)
HTTP				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:368)
HTTP				... 29 more
HTTP	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_x86_64
HTTP		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:224)
HTTP		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
HTTP		... 27 more
HTTP	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_x86_64.so
HTTP		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:171)
HTTP		... 28 more
HTTP		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_64 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
HTTP			at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
HTTP			at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
HTTP			at java.base/java.lang.System.loadLibrary(Unknown Source)
HTTP			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
HTTP			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:376)
HTTP			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:146)
HTTP			... 28 more
HTTP			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_64 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
HTTP				at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
HTTP				at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
HTTP				at java.base/java.lang.System.loadLibrary(Unknown Source)
HTTP				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
HTTP				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
HTTP				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
HTTP				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
HTTP				at java.base/java.lang.reflect.Method.invoke(Unknown Source)
HTTP				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:410)
HTTP				at java.base/java.security.AccessController.doPrivileged(Unknown Source)
HTTP				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:402)
HTTP				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:368)
HTTP				... 29 more
HTTP	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative
HTTP		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:224)
HTTP		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
HTTP		... 27 more
HTTP	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.so
HTTP		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:171)
HTTP		... 28 more
HTTP		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
HTTP			at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
HTTP			at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
HTTP			at java.base/java.lang.System.loadLibrary(Unknown Source)
HTTP			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
HTTP			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:376)
HTTP			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:146)
HTTP			... 28 more
HTTP			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
HTTP				at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
HTTP				at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
HTTP				at java.base/java.lang.System.loadLibrary(Unknown Source)
HTTP				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
HTTP				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
HTTP				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
HTTP				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
HTTP				at java.base/java.lang.reflect.Method.invoke(Unknown Source)
HTTP				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:410)
HTTP				at java.base/java.security.AccessController.doPrivileged(Unknown Source)
HTTP				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:402)
HTTP				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:368)
HTTP				... 29 more
HTTP
HTTP2022-02-24 06:43:37,775 DEBUG [io.net.han.ssl.OpenSsl] (vert.x-eventloop-thread-2) Initialize netty-tcnative using engine: 'default'
HTTP2022-02-24 06:43:37,777 DEBUG [io.net.han.ssl.OpenSsl] (vert.x-eventloop-thread-2) Failed to initialize netty-tcnative; OpenSslEngine will be unavailable. See https://netty.io/wiki/forked-tomcat-native.html for more information.: java.lang.UnsatisfiedLinkError: 'int io.netty.internal.tcnative.Library.aprMajorVersion()'
HTTP	at io.netty.internal.tcnative.Library.aprMajorVersion(Native Method)
HTTP	at io.netty.internal.tcnative.Library.initialize(Library.java:191)
HTTP	at io.netty.handler.ssl.OpenSsl.initializeTcNative(OpenSsl.java:710)
HTTP	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:163)
HTTP	at org.eclipse.hono.connection.impl.ConnectionFactoryImpl.addTlsTrustOptions(ConnectionFactoryImpl.java:383)
HTTP	at org.eclipse.hono.connection.impl.ConnectionFactoryImpl.addOptions(ConnectionFactoryImpl.java:360)
HTTP	at org.eclipse.hono.connection.impl.ConnectionFactoryImpl.connect(ConnectionFactoryImpl.java:144)
HTTP	at org.eclipse.hono.client.impl.HonoConnectionImpl$ConnectionAttempt.connect(HonoConnectionImpl.java:1096)
HTTP	at org.eclipse.hono.client.impl.HonoConnectionImpl$ConnectionAttempt.start(HonoConnectionImpl.java:1059)
HTTP	at org.eclipse.hono.client.impl.HonoConnectionImpl.lambda$connect$2(HonoConnectionImpl.java:387)
HTTP	at org.eclipse.hono.util.HonoProtonHelper.executeOnContext(HonoProtonHelper.java:230)
HTTP	at org.eclipse.hono.client.impl.HonoConnectionImpl.executeOnContext(HonoConnectionImpl.java:236)
HTTP	at org.eclipse.hono.client.impl.HonoConnectionImpl.connect(HonoConnectionImpl.java:377)
HTTP	at org.eclipse.hono.client.impl.HonoConnectionImpl.connect(HonoConnectionImpl.java:358)
HTTP	at org.eclipse.hono.client.impl.HonoConnectionImpl.connect(HonoConnectionImpl.java:352)
HTTP	at org.eclipse.hono.client.amqp.AbstractServiceClient.start(AbstractServiceClient.java:274)
HTTP	at org.eclipse.hono.client.notification.amqp.ProtonBasedNotificationReceiver.start(ProtonBasedNotificationReceiver.java:77)
HTTP	at org.eclipse.hono.util.WrappedLifecycleComponentVerticle.start(WrappedLifecycleComponentVerticle.java:41)
HTTP	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
HTTP	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
HTTP	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
HTTP	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
HTTP	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
HTTP	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
HTTP	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
HTTP	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
HTTP	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
HTTP	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
HTTP	at java.base/java.lang.Thread.run(Unknown Source)
HTTP
```

**Comment by sophokles73** [comment]
This might be due to the fact that when starting a Java application using the `-jar` switch, [all other classpath settings are ignored](https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#synopsis). So, if the jar in the `extensions` folder is not part of the transitive closure of the classpath defined in the applicaiton jar's manifest, then it would not be visible for the application's classloader ...
