### ISSUE TITLE
HTTP request with invalid 'origin' header is causing status 500 response (not 403)

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#3136]
When a client sends an HTTP request with an invalid `origin` header to the HTTP adapter or to the device registry, the response will contain status code 500 instead of 403.

Log output:
```
HTTP2022-03-03 18:08:53,529 DEBUG [org.ecl.hon.ser.htt.DefaultFailureHandler] (vert.x-eventloop-thread-1) handling failed route for request [method: OPTIONS, URI: http://127.0.0.1.nip.io:49340/telemetry, status: 403] - null: java.lang.IllegalStateException: CORS Rejected - Invalid origin
HTTP	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:211)
HTTP	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:41)
HTTP	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
HTTP	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
HTTP	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
HTTP	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:313)
[...]
HTTP2022-03-03 18:08:53,532 DEBUG [org.ecl.hon.ser.htt.DefaultFailureHandler] (vert.x-eventloop-thread-1) unexpected internal failure: java.lang.IllegalStateException: CORS Rejected - Invalid origin
HTTP	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:211)
HTTP	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:41)
HTTP	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
HTTP	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
HTTP	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
HTTP	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:313)
[...]
HTTP2022-03-03 18:08:53,546 TRACE [org.ecl.hon.ser.htt.ComponentMetaDataDecorator] (vert.x-eventloop-thread-1) logging failed processing of request
HTTP2022-03-03 18:08:53,547 WARN  [org.ecl.hon.tra.TracingHelper] (vert.x-eventloop-thread-1) An unexpected error occurred! [logged on span [8c7b43caea8b1942:8c7b43caea8b1942:0:1 - OPTIONS]]: java.lang.IllegalStateException: CORS Rejected - Invalid origin
HTTP	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:211)
HTTP	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:41)
HTTP	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
HTTP	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
HTTP	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
HTTP	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:313)
[...]
```
The Hono `DefaultFailureHandler` ignores the already set context status code 403 here and sets status 500.

**Comment by calohmn** [comment]
The `WARN` log line from `TracingHelper.logUnexpectedError()` could also be suppressed in this case. It gets invoked via `ComponentMetaDataDecorator.onFailure()`.
