### ISSUE TITLE
Fix integration tests that sometimes fail

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#3197]
When running the Hono integration tests in a local test environment, the
`org.eclipse.hono.tests.amqp.EventAmqpIT.testEventMessageAlreadySentIsDeliveredWhenConsumerConnects{VertxTestContext}`
was failing quite a few times.
To a lesser degree,
`org.eclipse.hono.tests.http.EventHttpIT.testEventMessageAlreadySentIsDeliveredWhenConsumerConnects{VertxTestContext}`
also showed errors.

From the test log output:
```
ERROR [CachingKafkaProducerFactory] producer error occurred 
[clientId: event-b2eafe55-636b-47a4-a13c-3ea20ed70047]: org.apache.kafka.common.errors.TimeoutException: 
Topic hono.event.4b4f9694-8631-402a-af52-58218f459aef not present in metadata after 500 ms.

[ERROR] testEventMessageAlreadySentIsDeliveredWhenConsumerConnects{VertxTestContext}  Time elapsed: 0.868 s  <<< ERROR!
org.eclipse.hono.client.amqp.connection.AmqpErrorException
	at org.eclipse.hono.tests.amqp.EventAmqpIT.lambda$testEventMessageAlreadySentIsDeliveredWhenConsumerConnects$4(EventAmqpIT.java:123)
```

<details>
<summary>Complete log excerpt</summary>

~~~
AMQP2022-04-04 13:01:33,612 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | event-b2eafe55-636b-47a4-a13c-3ea20ed70047) [Producer clientId=event-b2eafe55-636b-47a4-a13c-3ea20ed70047] Error while fetching metadata with correlation id 34 : {hono.event.4b82848e-cc9c-4610-87b2-1657756eff4e=LEADER_NOT_AVAILABLE}
AMQP2022-04-04 13:01:33,928 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | event-b2eafe55-636b-47a4-a13c-3ea20ed70047) [Producer clientId=event-b2eafe55-636b-47a4-a13c-3ea20ed70047] Error while fetching metadata with correlation id 35 : {hono.event.aa905216-48b9-4ffd-8534-8ace9e0ef947=LEADER_NOT_AVAILABLE, hono.event.a919a801-f1d3-4c7c-b677-85a9b78eb1f7=LEADER_NOT_AVAILABLE, hono.event.001a68d6-4d9a-4738-94d5-23dbab231da5=LEADER_NOT_AVAILABLE, hono.event.69bba0e0-055d-4967-97eb-ef0e84814a55=LEADER_NOT_AVAILABLE, hono.event.4fe1f77f-80c9-4cad-b383-f7551e37e1e9=LEADER_NOT_AVAILABLE, hono.event.d2637e20-cc3d-4539-8056-b6f4adeeb340=LEADER_NOT_AVAILABLE, hono.event.f2f33b06-f26e-4c52-a86c-5236ef85fb7c=LEADER_NOT_AVAILABLE, hono.event.d722df27-ac5b-4676-9ca3-360e12b35286=LEADER_NOT_AVAILABLE}
AMQP2022-04-04 13:01:36,890 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | event-b2eafe55-636b-47a4-a13c-3ea20ed70047) [Producer clientId=event-b2eafe55-636b-47a4-a13c-3ea20ed70047] Error while fetching metadata with correlation id 39 : {hono.event.de923d4c-fccd-45cd-8107-e03f13f487d1=LEADER_NOT_AVAILABLE}
AMQP2022-04-04 13:01:37,011 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | event-b2eafe55-636b-47a4-a13c-3ea20ed70047) [Producer clientId=event-b2eafe55-636b-47a4-a13c-3ea20ed70047] Error while fetching metadata with correlation id 40 : {hono.event.31612dd8-0f83-4956-ba8b-9865d2e94c9a=LEADER_NOT_AVAILABLE}
AMQP2022-04-04 13:01:40,131 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | event-b2eafe55-636b-47a4-a13c-3ea20ed70047) [Producer clientId=event-b2eafe55-636b-47a4-a13c-3ea20ed70047] Error while fetching metadata with correlation id 44 : {hono.event.5b0491b7-523c-4e72-8587-01e38d1c71da=LEADER_NOT_AVAILABLE}
AMQP2022-04-04 13:01:40,255 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | event-b2eafe55-636b-47a4-a13c-3ea20ed70047) [Producer clientId=event-b2eafe55-636b-47a4-a13c-3ea20ed70047] Error while fetching metadata with correlation id 45 : {hono.event.6db61680-2d93-4648-9db7-76d0c762bc86=LEADER_NOT_AVAILABLE}
...

15:02:33.303 [main] INFO  o.e.hono.tests.amqp.EventAmqpIT - running testEventMessageAlreadySentIsDeliveredWhenConsumerConnects(VertxTestContext)
15:02:33.304 [main] INFO  o.e.h.tests.IntegrationTestSupport - Configured to connect to Kafka on localhost:44801
15:02:33.306 [main] INFO  o.e.h.tests.IntegrationTestSupport - Configured to connect to Kafka on localhost:44801
15:02:33.307 [main] INFO  o.e.h.a.SpringBasedHonoPasswordEncoder - using BCrypt [strength: 4] with PRNG [NativePRNGNonBlocking] for encoding clear text passwords
15:02:33.640 [vert.x-eventloop-thread-1] INFO  o.e.hono.tests.amqp.EventAmqpIT - AMQPS connection to adapter [127.0.0.1.nip.io:49314] established
AMQP2022-04-04 13:02:33,694 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | event-b2eafe55-636b-47a4-a13c-3ea20ed70047) [Producer clientId=event-b2eafe55-636b-47a4-a13c-3ea20ed70047] Error while fetching metadata with correlation id 881 : {hono.event.4b4f9694-8631-402a-af52-58218f459aef=LEADER_NOT_AVAILABLE}
15:02:34.156 [main] INFO  o.e.h.tests.IntegrationTestSupport - connection to messaging network closed
AMQP2022-04-04 13:02:34,171 ERROR [org.ecl.hon.cli.kaf.pro.CachingKafkaProducerFactory] (vert.x-eventloop-thread-1) producer error occurred [clientId: event-b2eafe55-636b-47a4-a13c-3ea20ed70047]: org.apache.kafka.common.errors.TimeoutException: Topic hono.event.4b4f9694-8631-402a-af52-58218f459aef not present in metadata after 500 ms.
AMQP
15:02:34.174 [vert.x-eventloop-thread-1] INFO  o.e.hono.tests.amqp.EventAmqpIT - connection to AMQP adapter closed

[ERROR] Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 12.614 s <<< FAILURE! - in org.eclipse.hono.tests.amqp.EventAmqpIT
[ERROR] testEventMessageAlreadySentIsDeliveredWhenConsumerConnects{VertxTestContext}  Time elapsed: 0.868 s  <<< ERROR!
org.eclipse.hono.client.amqp.connection.AmqpErrorException
	at org.eclipse.hono.tests.amqp.EventAmqpIT.lambda$testEventMessageAlreadySentIsDeliveredWhenConsumerConnects$4(EventAmqpIT.java:123)


AMQP2022-04-04 13:02:34,194 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | event-b2eafe55-636b-47a4-a13c-3ea20ed70047) [Producer clientId=event-b2eafe55-636b-47a4-a13c-3ea20ed70047] Error while fetching metadata with correlation id 882 : {hono.event.9c393694-e031-437a-b1e0-62ccec48dcb7=LEADER_NOT_AVAILABLE, hono.event.ac7cf60d-7b7d-4272-8d89-831b5c6fc6e1=LEADER_NOT_AVAILABLE, hono.event.5b0491b7-523c-4e72-8587-01e38d1c71da=LEADER_NOT_AVAILABLE, hono.event.87d43af0-141c-46ee-94ad-f1e8ecc3fb19=LEADER_NOT_AVAILABLE, hono.event.a154d56d-c97b-45d2-a8f0-92117219211d=LEADER_NOT_AVAILABLE, hono.event.0398cc5a-82d9-4902-b187-a7c595c89f3a=LEADER_NOT_AVAILABLE, hono.event.4b82848e-cc9c-4610-87b2-1657756eff4e=LEADER_NOT_AVAILABLE, hono.event.871f3082-783b-4845-a74f-190522689672=LEADER_NOT_AVAILABLE, hono.event.de923d4c-fccd-45cd-8107-e03f13f487d1=LEADER_NOT_AVAILABLE, hono.event.e3506112-4361-40b1-9a9d-d233580b6c8d=LEADER_NOT_AVAILABLE, hono.event.30142a54-1257-4875-974c-e6b0ea5566f0=LEADER_NOT_AVAILABLE, hono.event.09caa4f8-9bc7-4620-9f65-3d3aa9e6b47a=LEADER_NOT_AVAILABLE, hono.event.6c023f23-956c-41d6-8a7f-2abe00b95250=LEADER_NOT_AVAILABLE}
AMQP2022-04-04 13:02:34,303 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | event-b2eafe55-636b-47a4-a13c-3ea20ed70047) [Producer clientId=event-b2eafe55-636b-47a4-a13c-3ea20ed70047] Error while fetching metadata with correlation id 883 : {hono.event.6c023f23-956c-41d6-8a7f-2abe00b95250=LEADER_NOT_AVAILABLE}
...
AMQP2022-04-04 13:06:18,204 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | event-b2eafe55-636b-47a4-a13c-3ea20ed70047) [Producer clientId=event-b2eafe55-636b-47a4-a13c-3ea20ed70047] Error while fetching metadata with correlation id 885 : {hono.event.bda778f4-7a7d-4f58-896a-7d19e9fa9786=LEADER_NOT_AVAILABLE, hono.event.4b4f9694-8631-402a-af52-58218f459aef=LEADER_NOT_AVAILABLE}
AMQP2022-04-04 13:06:18,534 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | command_response-4071a879-c245-4a8c-8e24-05ec8e5dd5c3) [Producer clientId=command_response-4071a879-c245-4a8c-8e24-05ec8e5dd5c3] Error while fetching metadata with correlation id 360 : {hono.command_response.0398cc5a-82d9-4902-b187-a7c595c89f3a=LEADER_NOT_AVAILABLE, hono.command_response.6c023f23-956c-41d6-8a7f-2abe00b95250=LEADER_NOT_AVAILABLE, hono.command_response.ac7cf60d-7b7d-4272-8d89-831b5c6fc6e1=LEADER_NOT_AVAILABLE}
~~~

</details>

**Comment by sophokles73** [comment]
@calohmn any idea yet why this is happening?

**Comment by calohmn** [comment]
It might be because test-tenant related Kafka topics get deleted in the tests too early (although we already apply a considerable delay) and then the Kafka blocks while repeatedly trying to get metadata for a topic that has already been deleted. 
We had such issues before (#2901, #2773). (On a production system, where such topics only get deleted with a long delay, I haven't seen such errors in quite a while.)
There's still the question why this is happening mostly with these 2 tests. I'll still have a closer look here.
