### ISSUE TITLE
MQTT adapter: Uncaught IllegalStateException: MQTT endpoint is closed

### ISSUE THREAD

**Issue by calohmn** [eclipse/hono#3377]
In integration test runs, there are such exceptions in the log:
```
ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-2) Uncaught exception received by Vert.x: 
java.lang.IllegalStateException: MQTT endpoint is closed
	at io.vertx.mqtt.impl.MqttEndpointImpl.checkClosed(MqttEndpointImpl.java:926)
	at io.vertx.mqtt.impl.MqttEndpointImpl.closeHandler(MqttEndpointImpl.java:367)
	at io.vertx.mqtt.impl.MqttEndpointImpl.closeHandler(MqttEndpointImpl.java:70)
	at org.eclipse.hono.adapter.mqtt.AbstractVertxBasedMqttProtocolAdapter$MqttDeviceEndpoint.close(AbstractVertxBasedMqttProtocolAdapter.java:1827)
	at org.eclipse.hono.adapter.mqtt.AbstractVertxBasedMqttProtocolAdapter.lambda$closeDeviceConnectionsOnDeviceOrTenantChange$15(AbstractVertxBasedMqttProtocolAdapter.java:418)
	at org.eclipse.hono.util.Futures.lambda$onCurrentContextCompletionHandler$5(Futures.java:192)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
```

**Comment by calohmn** [comment]
Fixed via 3c0ef9b0bf68f4ad849cb8ca9bb9e9856123c11d.
