### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#521]
During some tests is experienced the following behavior: Every once in a while I can see the following message in the logs:

~~~
Unhandled exception for connection:[id: 0x8c2f3716, L:0.0.0.0/0.0.0.0:8080 ! R:/10.128.0.1:53868]
12:17:48.585 [vert.x-eventloop-thread-3] ERROR i.vertx.core.net.impl.ConnectionBase - Unhandled exception for connection: {}
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:373)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
at java.lang.Thread.run(Thread.java:748)
~~~

Together with that the HTTP call to send payload (telemetry or event) gets 503 as a result. At some point this message starts to appear more frequently and also seem to cause delays in the HTTP call (see following screenshot).

Starting up an additional pod for the HTTP protocol adapters seems to improve the situation (red line marks the startup):

![image](https://user-images.githubusercontent.com/202474/36973876-eb1f8898-2074-11e8-8e0c-cf38ae52ab89.png)

I am creating this issue in order to track this issue and document any findings.

**Comment by ctron** [comment]
So I actually have a pretty good idea why this has happened. From the last scale test I did see this behavior with exactly one HTTP client, OkHttp. After the switch other some other HTTP client, this behavior was gone. My assumption would be that this is not actually a problem of Hono, but something related to OkHttp.
