### ISSUE TITLE
UsernamePasswordCredentials does not handle illegal Base64 strings

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#608]
When a client registers a *hashed-password* credential, the device registry does not validate the given password hash to comply with Base64 encoding. Thus, when the client registers an improper password hash, authentication fails when data is published from a device using the corresponding credentials.

In this case, `UsernamePasswordCredentials` fails with an uncaught IllegalArgumentException as shown below (in this case the password hash started with a single quote character):
```
07:19:41.952 [vert.x-eventloop-thread-0] ERROR i.v.e.w.impl.RoutingContextImplBase - Unexpected exception in route
java.lang.IllegalArgumentException: Illegal base64 character 27
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at org.eclipse.hono.service.auth.device.UsernamePasswordCredentials.matchesCredentials(UsernamePasswordCredentials.java:151)
	at org.eclipse.hono.service.auth.device.AbstractDeviceCredentials.lambda$validate$1(AbstractDeviceCredentials.java:55)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
```

**Comment by sophokles73** [comment]
We should probably do both, check a hashed password for compliance with Base64 encoding and catch the InvalidArgumentException in order to return a proper status code during authentication in the protocol adapter.
