### ISSUE TITLE
Half dead HTTP adapter instances

### ISSUE THREAD

**Issue by ctron** [eclipse/hono#735]
Every now and then it happens to me that an HTTP protocol adapter instance is half dead. It is being reported as healthy, yet does not send any messages to the downstream Qpid router. HTTP requests return 503.

The following two exceptions keep repeating over and over:

~~~
08:21:33.966 [vert.x-eventloop-thread-0] ERROR i.v.e.w.impl.RoutingContextImplBase - Unexpected exception in route
java.lang.IllegalStateException: Response is closed
	at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:548)
	at io.vertx.core.http.impl.HttpServerResponseImpl.end0(HttpServerResponseImpl.java:401)
	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:319)
	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:308)
	at io.vertx.ext.web.impl.RoutingContextImplBase.unhandledFailure(RoutingContextImplBase.java:166)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:132)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.opentracing.contrib.vertx.ext.web.TracingHandler.handlerFailure(TracingHandler.java:90)
	at io.opentracing.contrib.vertx.ext.web.TracingHandler.handle(TracingHandler.java:44)
	at io.opentracing.contrib.vertx.ext.web.TracingHandler.handle(TracingHandler.java:25)
	at io.vertx.ext.web.impl.RouteImpl.handleFailure(RouteImpl.java:223)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:117)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.vertx.ext.web.impl.RoutingContextImpl.doFail(RoutingContextImpl.java:465)
	at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:166)
	at org.eclipse.hono.service.auth.device.HonoAuthHandler.processException(HonoAuthHandler.java:233)
	at org.eclipse.hono.service.auth.device.HonoAuthHandler.lambda$null$1(HonoAuthHandler.java:189)
	at org.eclipse.hono.service.auth.device.CredentialsApiAuthProvider.lambda$authenticate$3(CredentialsApiAuthProvider.java:127)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.Future.lambda$map$2(Future.java:308)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:149)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at io.vertx.core.impl.FailedFuture.setHandler(FailedFuture.java:48)
	at io.vertx.core.Future.lambda$recover$4(Future.java:392)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:149)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.Future.lambda$map$2(Future.java:308)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:149)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at org.eclipse.hono.client.impl.AbstractRequestResponseClient.cancelRequest(AbstractRequestResponseClient.java:416)
	at org.eclipse.hono.client.impl.AbstractRequestResponseClient.lambda$null$3(AbstractRequestResponseClient.java:729)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
~~~

~~~
08:21:33.968 [vert.x-eventloop-thread-0] ERROR i.v.e.w.impl.RoutingContextImplBase - Unexpected exception in route
java.lang.IllegalStateException: Response is closed
	at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:548)
	at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:189)
	at org.eclipse.hono.service.http.HttpUtils.setResponseBody(HttpUtils.java:318)
	at org.eclipse.hono.service.http.DefaultFailureHandler.sendError(DefaultFailureHandler.java:110)
	at org.eclipse.hono.service.http.DefaultFailureHandler.handle(DefaultFailureHandler.java:60)
	at org.eclipse.hono.service.http.DefaultFailureHandler.handle(DefaultFailureHandler.java:40)
	at io.vertx.ext.web.impl.RouteImpl.handleFailure(RouteImpl.java:223)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:117)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.opentracing.contrib.vertx.ext.web.TracingHandler.handlerFailure(TracingHandler.java:90)
	at io.opentracing.contrib.vertx.ext.web.TracingHandler.handle(TracingHandler.java:44)
	at io.opentracing.contrib.vertx.ext.web.TracingHandler.handle(TracingHandler.java:25)
	at io.vertx.ext.web.impl.RouteImpl.handleFailure(RouteImpl.java:223)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:117)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.vertx.ext.web.impl.RoutingContextImpl.doFail(RoutingContextImpl.java:465)
	at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:166)
	at org.eclipse.hono.service.auth.device.HonoAuthHandler.processException(HonoAuthHandler.java:233)
	at org.eclipse.hono.service.auth.device.HonoAuthHandler.lambda$null$1(HonoAuthHandler.java:189)
	at org.eclipse.hono.service.auth.device.CredentialsApiAuthProvider.lambda$authenticate$3(CredentialsApiAuthProvider.java:127)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.Future.lambda$map$2(Future.java:308)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:149)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at io.vertx.core.impl.FailedFuture.setHandler(FailedFuture.java:48)
	at io.vertx.core.Future.lambda$recover$4(Future.java:392)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:149)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.Future.lambda$map$2(Future.java:308)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:149)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at org.eclipse.hono.client.impl.AbstractRequestResponseClient.cancelRequest(AbstractRequestResponseClient.java:416)
	at org.eclipse.hono.client.impl.AbstractRequestResponseClient.lambda$null$3(AbstractRequestResponseClient.java:729)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
~~~

The full log is here: [hono-adapter-http-vertx.log](https://github.com/eclipse/hono/files/2235097/hono-adapter-http-vertx.log)

However I am not sure if this repeating exception is the cause of just a side effect. In any case I think that the exception caused by calling into `putHeader` on a closed response should be handled or avoided in the first place.

**Comment by sophokles73** [comment]
The log file seems to refer to a *custom* implementation of `DefaultFailureHandler`. The implementation on master only contains 89 lines. That said, it is unclear, which class in the stack has actually ended the response before the default handler kicked in. In any case, we should make `HttpUtils` and the `DefaultFailureHandler` more *defensive* in that they should check if the response is not yet ended before trying to set headers and body.

**Comment by ctron** [comment]
The root cause of the problem is something different IMHO. To me it looks like the requests are not being completed properly and pile up in the internal request cache.

**Comment by ctron** [comment]
Please ignore that last one. The correlation ID of the result should be either the correlation ID or the message ID of the request.

**Comment by ctron** [comment]
I any case, the issue with the half-dead instances still is a problem.

**Comment by sophokles73** [comment]
> Every now and then it happens to me that an HTTP protocol adapter instance is half dead. It is being reported as healthy, yet does not send any messages to the downstream Qpid router. HTTP requests return 503.

This sounds like *works as designed", assuming that the protocol adapter simply does not get credits fast enough from the downstream consumers ...

**Comment by sophokles73** [comment]
In any case, there *was* a problem with writing to an already closed response, which has been fixed. Thus, I think we should change the title of this issue and close it in order to track this progress. You may then open another issue regarding the behavior which you perceive as erroneous ...

**Comment by sophokles73** [comment]
Still, can we then create a separate issue for it?

**Comment by ctron** [comment]
What would be the benefit of creating a new issue if the current one describes the problem?

There is a screenshot of how that looks in the enmasse console:

![image](https://user-images.githubusercontent.com/202474/43384258-c1cad5ba-93dd-11e8-95ae-8a105fa46f47.png)

The protocol adapter now returns 100% 503s, but should have a credit of 5.000.

**Comment by ctron** [comment]
The body of the HTTP response contains: `no credit available for sending request`. From what I see, this can only be generated by the `AbstractRequestResponseClient` and would most likely mean that the protocol adapter didn't receive any credits from the device registry.

Which would explain why this sometimes auto-fixes itself after 10 minutes.

But why doesn't the device registry give hand out credits?

**Comment by sophokles73** [comment]
@ctron this seems to have been addressed by your recent PR. Can we (i.e. you) close this issue?

**Comment by ctron** [comment]
Yes, indeed.
