### ISSUE TITLE
MQTT adapter looses connection to Hono Messaging and does not try to reconnect

### ISSUE THREAD

**Issue by chapitos** [eclipse/hono#772]
We have noticed, after performing a rolling update of the Kubernetes cluster where Hono is running, that one of the MQTT adapters was in not ready state. As expected, since Hono messaging was also being re-scheduled on new nodes (due to rolling update of the Kubernets cluster), MQTT adapter was repeatedly trying to connect to Hono messaging service and failed 30 times, as Hono messaging was still not up and running. On the 31st attempt it has succeeded:

```05:29:32.650 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.HonoClientImpl - starting attempt [#31] to connect to server [Con:5672]
05:29:32.650 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connecting to AMQP 1.0 container [amqp://messaging.hono:5672]
05:29:32.835 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connected to AMQP 1.0 container [amqp://messaging.hono:5672], opening connection ...
05:29:32.837 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connection to container [Router.qdrouterd-5656949bcc-7prjt] at [amqp://messaging.hono:5672] open
```

So far so good.

A bit later, though, the MQTT adapter looses connection to all needed service: Device Registry, Tenant Manager, Credentials Service and Hono Messaging. The connection is re-established a while later to all the listed services except to Hono messaging:

```
05:36:01.040 [vert.x-eventloop-thread-0] DEBUG o.e.h.client.impl.AbstractHonoClient - opening sender [telemetry/t3dfd5f5d4769472983a60303037460e6] failed: amqp:precondition-failed - no consumer available for target
05:36:01.041 [vert.x-eventloop-thread-0] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: Result is already complete: failed
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:98)
	at org.eclipse.hono.client.impl.AbstractHonoClient.lambda$null$5(AbstractHonoClient.java:369)
	at io.vertx.proton.impl.ProtonLinkImpl.fireRemoteOpen(ProtonLinkImpl.java:308)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:133)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:384)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessageReceived(NetSocketImpl.java:351)
	at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:242)
	at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:239)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1380)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1159)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1194)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
05:36:01.041 [vert.x-eventloop-thread-0] INFO  o.e.hono.client.impl.HonoClientImpl - remote server [hono-service-device-registry.hono:5671] closed connection with error condition: Error{condition=amqp:unauthorized-access, description='access token expired', info=null}
05:36:01.043 [vert.x-eventloop-thread-0] INFO  o.e.hono.client.impl.HonoClientImpl - remote server [hono-service-tenant-manager.hono:5671] closed connection with error condition: Error{condition=amqp:unauthorized-access, description='access token expired', info=null}
05:36:01.043 [vert.x-eventloop-thread-0] INFO  o.e.hono.client.impl.HonoClientImpl - remote server [hono-service-device-registry.hono:5671] closed connection with error condition: Error{condition=amqp:unauthorized-access, description='access token expired', info=null}
05:36:01.044 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.HonoClientImpl - lost connection to server [hono-service-messaging.hono:5671]
05:36:01.044 [vert.x-eventloop-thread-0] DEBUG o.e.h.a.m.i.VertxBasedMqttProtocolAdapter - cannot establish connection with device [tenant-id: HEALTH_CHECK_TENANT, auth-id: test_51066365082799515]
org.eclipse.hono.client.ServerErrorException: no connection to service
	at org.eclipse.hono.client.impl.HonoClientImpl.lambda$getOrCreateSender$16(HonoClientImpl.java:613)
	at org.eclipse.hono.client.impl.HonoClientImpl.failAllCreationRequests(HonoClientImpl.java:457)
	at org.eclipse.hono.client.impl.HonoClientImpl.clearState(HonoClientImpl.java:449)
	at org.eclipse.hono.client.impl.HonoClientImpl.handleConnectionLoss(HonoClientImpl.java:430)
	at org.eclipse.hono.client.impl.HonoClientImpl.onRemoteDisconnect(HonoClientImpl.java:419)
	at org.eclipse.hono.client.impl.HonoClientImpl.lambda$null$3(HonoClientImpl.java:357)
	at io.vertx.proton.impl.ProtonConnectionImpl.fireDisconnect(ProtonConnectionImpl.java:374)
	at io.vertx.proton.impl.ProtonTransport.handleSocketEnd(ProtonTransport.java:89)
	at io.vertx.core.net.impl.NetSocketImpl.handleClosed(NetSocketImpl.java:340)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:130)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.stream.ChunkedWriteHandler.channelInactive(ChunkedWriteHandler.java:143)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1010)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
05:36:01.044 [vert.x-eventloop-thread-0] DEBUG o.e.h.a.m.i.VertxBasedMqttProtocolAdapter - connection request from client [clientId: test_51066365082799515] rejected with code: CONNECTION_REFUSED_SERVER_UNAVAILABLE
05:36:01.044 [vert.x-eventloop-thread-0] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: MQTT endpoint is closed
	at io.vertx.mqtt.impl.MqttEndpointImpl.checkClosed(MqttEndpointImpl.java:689)
	at io.vertx.mqtt.impl.MqttEndpointImpl.write(MqttEndpointImpl.java:677)
	at io.vertx.mqtt.impl.MqttEndpointImpl.connack(MqttEndpointImpl.java:298)
	at io.vertx.mqtt.impl.MqttEndpointImpl.reject(MqttEndpointImpl.java:326)
	at io.vertx.mqtt.impl.MqttEndpointImpl.reject(MqttEndpointImpl.java:47)
	at org.eclipse.hono.adapter.mqtt.AbstractVertxBasedMqttProtocolAdapter.handleConnectionRequestResult(AbstractVertxBasedMqttProtocolAdapter.java:366)
	at org.eclipse.hono.adapter.mqtt.AbstractVertxBasedMqttProtocolAdapter.lambda$handleEndpointConnection$9(AbstractVertxBasedMqttProtocolAdapter.java:315)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:149)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:149)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at io.vertx.core.impl.FailedFuture.setHandler(FailedFuture.java:48)
	at io.vertx.core.Future.lambda$recover$4(Future.java:392)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:149)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.Future.lambda$compose$1(Future.java:272)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.Future.lambda$map$2(Future.java:308)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:97)
	at io.vertx.core.Future.lambda$map$2(Future.java:308)
	at io.vertx.core.impl.CompositeFutureImpl.lambda$all$1(CompositeFutureImpl.java:49)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:165)
	at org.eclipse.hono.client.impl.HonoClientImpl.lambda$getOrCreateSender$16(HonoClientImpl.java:613)
	at org.eclipse.hono.client.impl.HonoClientImpl.failAllCreationRequests(HonoClientImpl.java:457)
	at org.eclipse.hono.client.impl.HonoClientImpl.clearState(HonoClientImpl.java:449)
	at org.eclipse.hono.client.impl.HonoClientImpl.handleConnectionLoss(HonoClientImpl.java:430)
	at org.eclipse.hono.client.impl.HonoClientImpl.onRemoteDisconnect(HonoClientImpl.java:419)
	at org.eclipse.hono.client.impl.HonoClientImpl.lambda$null$3(HonoClientImpl.java:357)
	at io.vertx.proton.impl.ProtonConnectionImpl.fireDisconnect(ProtonConnectionImpl.java:374)
	at io.vertx.proton.impl.ProtonTransport.handleSocketEnd(ProtonTransport.java:89)
	at io.vertx.core.net.impl.NetSocketImpl.handleClosed(NetSocketImpl.java:340)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:130)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.stream.ChunkedWriteHandler.channelInactive(ChunkedWriteHandler.java:143)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1010)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
05:36:01.542 [vert.x-eventloop-thread-0] INFO  o.e.h.a.m.i.VertxBasedMqttProtocolAdapter - attempting to reconnect to Device Registration service
05:36:01.543 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.HonoClientImpl - starting attempt [#1] to connect to server [hono-service-device-registry.hono:5671]
05:36:01.543 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - OpenSSL [available: true, supports KeyManagerFactory: true, supports Hostname validation: true]
05:36:01.543 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - using OpenSSL [version: BoringSSL] instead of JDK's default SSL engine
05:36:01.543 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - enabling secure protocol [TLSv1.2]
05:36:01.543 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connecting to AMQP 1.0 container [amqps://hono-service-device-registry.hono:5671]
05:36:01.548 [vert.x-eventloop-thread-0] INFO  o.e.h.a.m.i.VertxBasedMqttProtocolAdapter - attempting to reconnect to Tenant service
05:36:01.548 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.HonoClientImpl - starting attempt [#1] to connect to server [hono-service-tenant-manager.hono:5671]
05:36:01.548 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - OpenSSL [available: true, supports KeyManagerFactory: true, supports Hostname validation: true]
05:36:01.548 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - using OpenSSL [version: BoringSSL] instead of JDK's default SSL engine
05:36:01.548 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - enabling secure protocol [TLSv1.2]
05:36:01.548 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connecting to AMQP 1.0 container [amqps://hono-service-tenant-manager.hono:5671]
05:36:01.551 [vert.x-eventloop-thread-0] INFO  o.e.h.a.m.i.VertxBasedMqttProtocolAdapter - attempting to reconnect to Credentials service
05:36:01.551 [vert.x-eventloop-thread-0] DEBUG o.e.hono.client.impl.HonoClientImpl - starting attempt [#1] to connect to server [hono-service-device-registry.hono:5671]
05:36:01.551 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - OpenSSL [available: true, supports KeyManagerFactory: true, supports Hostname validation: true]
05:36:01.551 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - using OpenSSL [version: BoringSSL] instead of JDK's default SSL engine
05:36:01.552 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - enabling secure protocol [TLSv1.2]
05:36:01.552 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connecting to AMQP 1.0 container [amqps://hono-service-device-registry.hono:5671]
05:36:01.673 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connected to AMQP 1.0 container [amqps://hono-service-tenant-manager.hono:5671], opening connection ...
05:36:01.676 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connection to container [IoTHub-TenantManager-0.0.0.0:5671] at [amqps://hono-service-tenant-manager.hono:5671] open
05:36:01.676 [vert.x-eventloop-thread-0] INFO  o.e.h.a.m.i.VertxBasedMqttProtocolAdapter - reconnected to Tenant service
05:36:01.738 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connected to AMQP 1.0 container [amqps://hono-service-device-registry.hono:5671], opening connection ...
05:36:01.741 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connection to container [IoTHub-DeviceRegistry-0.0.0.0:5671] at [amqps://hono-service-device-registry.hono:5671] open
05:36:01.741 [vert.x-eventloop-thread-0] INFO  o.e.h.a.m.i.VertxBasedMqttProtocolAdapter - reconnected to Device Registration service
05:36:01.756 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connected to AMQP 1.0 container [amqps://hono-service-device-registry.hono:5671], opening connection ...
05:36:01.758 [vert.x-eventloop-thread-0] DEBUG o.e.h.c.impl.ConnectionFactoryImpl - connection to container [IoTHub-DeviceRegistry-0.0.0.0:5671] at [amqps://hono-service-device-registry.hono:5671] open
05:36:01.758 [vert.x-eventloop-thread-0] INFO  o.e.h.a.m.i.VertxBasedMqttProtocolAdapter - reconnected to Credentials service
```
The MQTT adapter does not attempt to re-establish the connection to the Hono Messaging service going forward (in contrast to other services where attempts to reconnect are done every 10 minutes after access token expiration). It seems that MQTT adapter assumes that the connection to Hono messaging is there and valid. The effect of the described state is that the Hono readiness check fails and the pod is labelled as 'Not Ready' in the Kubernetes cluster.

It seems that the MQTT adapter has run into a non-recoverable state.

**Comment by pellmann** [comment]
@chapitos - which Hono version do you use?

**Comment by sophokles73** [comment]
it appears to be 0.7-M2

**Comment by sophokles73** [comment]
@chapitos do you happen to have more of the log file, i.e. logs of what happened after the last entry of the log you posted? I would be interested in what happens for, say, the next 2 minutes ...

**Comment by chapitos** [comment]
@pellmann 0.7 M2
@sophokles73 Attached is the complete MQTT PA log file.
[mqtt-notready.log](https://github.com/eclipse/hono/files/2310891/mqtt-notready.log)

**Comment by sophokles73** [comment]
@chapitos is this still an issue for you? If not, can you close this issue?

**Comment by chapitos** [comment]
@sophokles73 : have not seen this issue in a long time. Please close.
