### ISSUE TITLE
"No context to run" exception thrown every time HonoClient is instantiated

### ISSUE THREAD

**Issue by balsmn** [eclipse/hono#776]
Quite recently we migrated to Hono 0.7-M2 and are observing the following exception, every time when the HonoClient is retrieved/instantiated in the Http Protocol Adatper (~ every 10 Minutes)

But the overall system is working (telemetry and event), I suppose due to retries. So the below exception is not blocking but interested to know if something is wrong.

```
java.lang.IllegalStateException: no context to run on
	at org.eclipse.hono.util.HonoProtonHelper.executeOrRunOnContext(HonoProtonHelper.java:251)
	at org.eclipse.hono.client.impl.HonoClientImpl.executeOrRunOnContext(HonoClientImpl.java:204)
	at org.eclipse.hono.client.impl.HonoClientImpl.getOrCreateRequestResponseClient(HonoClientImpl.java:986)
	at org.eclipse.hono.client.impl.HonoClientImpl.getOrCreateTenantClient(HonoClientImpl.java:881)
	at org.eclipse.hono.service.AbstractProtocolAdapterBase.getTenantClient(AbstractProtocolAdapterBase.java:127)
	at org.eclipse.hono.service.AbstractProtocolAdapterBase.getTenantConfiguration(AbstractProtocolAdapterBase.java:644)
	at org.eclipse.hono.adapter.http.AbstractVertxBasedHttpProtocolAdapter.doUploadMessage(AbstractVertxBasedHttpProtocolAdapter.java:572)
	at org.eclipse.hono.adapter.http.AbstractVertxBasedHttpProtocolAdapter.uploadTelemetryMessage(AbstractVertxBasedHttpProtocolAdapter.java:490)
	at org.eclipse.hono.adapter.http.AbstractVertxBasedHttpProtocolAdapter.uploadTelemetryMessage(AbstractVertxBasedHttpProtocolAdapter.java:464)
	at org.eclipse.hono.adapter.http.vertx.VertxBasedHttpProtocolAdapter.handlePostTelemetry(VertxBasedHttpProtocolAdapter.java:285)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:219)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:120)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at org.eclipse.hono.service.auth.device.HonoAuthHandler.lambda$authorizeUser$3(HonoAuthHandler.java:250)
	at org.eclipse.hono.service.auth.device.HonoAuthHandler.authorize(HonoAuthHandler.java:127)
	at org.eclipse.hono.service.auth.device.HonoAuthHandler.authorizeUser(HonoAuthHandler.java:244)
	at org.eclipse.hono.service.auth.device.HonoAuthHandler.lambda$null$1(HonoAuthHandler.java:181)
	at org.eclipse.hono.service.auth.device.CredentialsApiAuthProvider.lambda$authenticate$3(CredentialsApiAuthProvider.java:125)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:121)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:83)
	at io.vertx.core.Future.lambda$map$2(Future.java:306)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:121)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:83)
	at io.vertx.core.Future.lambda$recover$4(Future.java:383)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:121)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:83)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:147)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:121)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:83)
	at io.vertx.core.Future.lambda$map$2(Future.java:306)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:121)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:83)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:147)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at org.eclipse.hono.client.impl.AbstractRequestResponseClient.handleResponse(AbstractRequestResponseClient.java:386)
	at org.eclipse.hono.client.impl.AbstractHonoClient.lambda$null$9(AbstractHonoClient.java:418)
	at io.vertx.proton.impl.ProtonReceiverImpl.onDelivery(ProtonReceiverImpl.java:183)
	at io.vertx.proton.impl.ProtonTransport.handleSocketBuffer(ProtonTransport.java:158)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:384)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessageReceived(NetSocketImpl.java:351)
	at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:242)
	at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:239)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1380)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1159)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1194)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sophokles73** [comment]
@balsmn I have taken a look at the code. This seems to be a case of *works as designed*. The adapter tries to get a TenantClient instance but the underlying AMQP connection is not (yet) established. The exception is thrown from a generic method for execution code on a specific (i.e. the correct) vert.x Context. In this case the context is `null` because the connection that is supposed to have been established on that context is `null` as well.

We should introduce an explicit check for the connection being `null` in `HonoClientImpl`'s factory methods and then fail the future with a standard `ServerErrorException` with a 503 code ...
