### ISSUE TITLE
MQTT protocol adapter Docker image does not start

### ISSUE THREAD

**Issue by sophokles73** [eclipse/hono#78]
The MQTT protocol adapter Spring Boot application fails to start with a ClassNotFoundException:

> mqtt-adapter_1  | 11:54:20.154 [main] INFO  o.e.hono.adapter.mqtt.Application - Starting Application on bf1580c30cec with PID 1 (/opt/hono/hono-adapter-mqtt-vertx-0.5-M3-SNAPSHOT.jar started by hono in /home/hono)
mqtt-adapter_1  | 11:54:20.166 [main] DEBUG o.e.hono.adapter.mqtt.Application - Running with Spring Boot v1.4.0.RELEASE, Spring v4.3.2.RELEASE
mqtt-adapter_1  | 11:54:20.179 [main] INFO  o.e.hono.adapter.mqtt.Application - The following profiles are active: dev
mqtt-adapter_1  | 11:54:20.332 [main] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@736e9adb: startup date [Tue Dec 13 11:54:20 GMT 2016]; root of context hierarchy
mqtt-adapter_1  | 11:54:22.982 [main] DEBUG o.e.h.a.m.Application$$EnhancerBySpringCGLIB$$dd565d54 - starting up 1 instances of 'MQTT' adapter verticle
mqtt-adapter_1  | 11:54:22.988 [main] WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: io/vertx/mqtt/MqttEndpoint
mqtt-adapter_1  | 11:54:23.019 [main] INFO  o.s.b.a.l.AutoConfigurationReportLoggingInitializer - 
mqtt-adapter_1  | 
mqtt-adapter_1  | Error starting ApplicationContext. To display the auto-configuration report enable debug logging (start with --debug)
mqtt-adapter_1  | 
mqtt-adapter_1  | 
mqtt-adapter_1  | 11:54:23.075 [main] ERROR o.s.boot.SpringApplication - Application startup failed
mqtt-adapter_1  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: io/vertx/mqtt/MqttEndpoint
mqtt-adapter_1  | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
mqtt-adapter_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
mqtt-adapter_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]
mqtt-adapter_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.3.2.RELEASE.jar!/:4.3.2.RELEASE]

I suspect this is because the now *system* scoped dependency on vertx-mqtt-server is not included in the *uber*-jar (because of the scope)...

**Comment by sophokles73** [comment]
Fixed in f6b306303feb472cb10f281db779a773273b68ab
