### ISSUE TITLE
System.setProperty("vertx.disableTCCL", "true"); caused sender unable to connect 500 error

### ISSUE THREAD

**Issue by KeiranHines** [eclipse/hono#823]
Hi, 

I am currently trying to get a Java based sender connected to eclipse Hono and am stuck on the following issue with security access control. 
If I create a normal vertx using Vertx.Vertx() I get a securityControlException 
`java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "setContextClassLoader")
 at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
 at java.security.AccessController.checkPermission(AccessController.java:884)
 at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
 at java.lang.Thread.setContextClassLoader(Thread.java:1474)
 at io.netty.util.concurrent.GlobalEventExecutor.startThread(GlobalEventExecutor.java:223)
 at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:211)
 at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:760)
 at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
 at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:925)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.lang.Thread.run(Thread.java:748)`
I am unable to grant this permission on my system. To work around this I set the system property vertx.disableTCCL to true. However this causes me to be unable to connect Hono, all I receive is 500 errors. 

I am unable to determine if this is a bug in Hono or a bug in my code. 
Thank-you, 
Keiran.

**Comment by sophokles73** [comment]
Hi,

I am not sure if I understand what you are trying to achieve. Can you elaborate a little and (ideally) post the code (or a gist) that you are trying to run?

**Comment by sophokles73** [comment]
@KeiranHines can you provide more information?
